import React, { createContext, useState, useEffect } from "react";

export const translations = {
  fr: {
    home: "Accueil",
    researchers: "Chercheurs",
    publications: "Publications",
    news: "Actualités",
    about: "À propos",
    contact: "Contact",
    login: "Connexion",
    logout: "Déconnexion",
    myAccount: "Mon compte",
    settings: "Paramètres",
    language: "Langue",
    theme: "Thème",
    switchLanguage: "Changer la langue",
    calendar: "Calendrier",
    list: "Liste",
    next: "Suivant",
    previous: "Précédent",
    today: "Aujourd'hui",
    month: "Mois",
    week: "Semaine",
    day: "Jour",
    events: "Événements",
    showMore: "Voir plus",
    error404: "Page non trouvée",
    pageNotFound: "Désolé, nous n'avons pas trouvé la page que vous cherchez.",
    backToHome: "Retour à l'accueil",
    searchPublications: "Rechercher des publications...",
    filter: "Filtrer",
    year: "Année",
    domain: "Domaine",
    activeResearchers: "Chercheurs Actifs",
    citations: "Citations",
    profileError: "Erreur de récupération du profil",
    help: "Aide",
    contactSupport: "Contacter le support",
    more: "plus",
    loading: "Chargement...",
    welcomeMessage: "Bienvenue, {name}} !",
    appearance: "Apparence",
    lightTheme: "Thème clair",
    darkTheme: "Thème sombre",
    systemTheme: "Système",
    french: "Français",
    english: "Anglais",
    save: "Sauvegarder",
    close: "Fermer",
    back: "Retour",
    share: "Partager",
    comments: "Commentaires",
    downloadPDF: "Télécharger le PDF",
    abstract: "Résumé",
    name: "Nom",
    department: "Département",
    homeTitle: "Facilitez l’Accès aux Profils de Recherche",
    homeSubtitle:
      "Trouvez facilement les informations des chercheurs et leurs travaux scientifiques.",
    pageNotFoundTitle: "Page non trouvée",
    pageNotFoundDesc:
      "Désolé, nous n'avons pas trouvé la page que vous cherchez.",
    exploreResearchers: "Explorer les Chercheurs",
    learnMore: "En savoir plus",
    researchersCount: "Chercheurs",
    publicationsCount: "Publications",
    projectsCount: "Projets",
    countriesCount: "Pays",
    homeWelcomeTitle:
      "Bienvenue sur le Portail des Chercheurs [Page en cours de développement]",
    homeWelcomeText:
      "Accédez aux profils des chercheurs, découvrez leurs travaux et explorez les collaborations possibles.",
    abstractTitle: "Résumé",
    fullTextTitle: "Contenu Intégral",
    statsTitle: "Statistiques",
    citationsLabel: "Citations",
    downloadsLabel: "Téléchargements",
    downloadPdfBtn: "Télécharger le PDF",
    viewCitationsBtn: "Voir les citations",
    relatedPubsTitle: "Publications Associées",
    backBtnAria: "Retour",
    actualiteNotFoundTitle: "Actualité non trouvée",
    actualiteNotFoundDesc:
      "L'actualité demandée n'existe pas ou a été supprimée",
    dateLabel: "Le",
    categoryLabel: "Catégorie",
    backButton: "Retour",
    shareButton: "Partager",
    commentsTitle: "Commentaires",
    addCommentPlaceholder: "Ajouter un commentaire...",
    postCommentButton: "Publier",
    chercheursTitle: "Chercheurs",
    filterButton: "Filtrer",
    filterByName: "Nom",
    filterByDepartment: "Département",
    filterByPublications: "Publications",
    errorLoadingData: "Erreur lors du chargement des données",
    noResults: "Aucun résultat",
    closeButtonAria: "Fermer",
    agenda: "Agenda",
    adminNewsTitle: "Gestion des Actualités",
    adminDisciplineTitle: "Gestion des Disciplines",
    addButton: "Ajouter",
    filterAll: "Toutes",
    filterFuture: "À venir",
    filterArchive: "Archivées",
    tableHeaderTitle: "Titre",
    tableHeaderLocation: "Localisation",
    tableHeaderDate: "Date",
    tableHeaderCategory: "Catégorie",
    tableHeaderActions: "Actions",
    noNewsFound: "Aucune actualité trouvée.",
    confirmDelete: "Confirmer la suppression ?",
    adminResearchersTitle: "Gestion des Chercheurs",
    adminLoginTitle: "Authentification Administrateur",
    emailLabel: "Email",
    emailPlaceholder: "admin@example.com",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "••••••••",
    loginButton: "Se connecter",
    dashboardTitle: "Tableau de bord",
    createNewsTitle: "Créer une actualité",
    titrePlaceholder: "Titre",
    locationPlaceholder: "Localisation",
    descriptionPlaceholder: "Description",
    categoryPlaceholder: "Catégorie",
    creationSuccess: "Actualité ajoutée avec succès !",
    creationError: "Erreur lors de l'ajout !",
    createResearcherTitle: "Créer un compte Chercheur",
    firstNameLabel: "Prénom",
    firstNamePlaceholder: "Prénom",
    lastNameLabel: "Nom",
    lastNamePlaceholder: "Nom",
    createAccountButton: "Créer le compte",
    researcherCreationSuccess: "Chercheur créé avec succès !",
    researcherCreationErrorPrefix: "Erreur lors de la création : ",
    unknownError: "Erreur inconnue",
    changePasswordTitle: "Changer le mot de passe",
    currentPasswordLabel: "Mot de passe actuel",
    currentPasswordPlaceholder: "••••••••",
    newPasswordLabel: "Nouveau mot de passe",
    newPasswordPlaceholder: "••••••••",
    confirmPasswordLabel: "Confirmer le nouveau mot de passe",
    confirmPasswordPlaceholder: "••••••••",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    passwordChangeSuccess: "Mot de passe changé avec succès !",
    passwordChangeError:
      "Une erreur s'est produite lors du changement de mot de passe.",
    completeProfileFormTitle: "Complétez votre profil",
    scopusIdPlaceholder: "ID Scopus",
    disciplinePlaceholder: "Discipline",
    submitButton: "Valider",
    statPublications: "Publications",
    statResearchers: "Chercheurs",
    statVisitors: "Visiteurs",
    chartTitle: "Statistiques des chercheurs",
    chartLabelResearchers: "Chercheurs",
    monthDec: "Déc",
    monthJan: "Jan",
    monthFeb: "Fév",
    monthMar: "Mar",
    monthApr: "Avr",
    monthMay: "Mai",
    monthJun: "Juin",
    upcomingEventTitle: "Événements",
    upcomingEventDesc:
      "Découvrez les nouveautés et préparez-vous pour le prochain événement",
    viewMoreButton: "Voir plus",
    statsLoadError: "Erreur lors du chargement des statistiques :",
    profileLoadError: "Impossible de charger le profil.",
    universityLabel: "Université",
    contactButton: "Contacter",
    editButton: "Modifier",
    infoTitle: "Informations",
    locationLabel: "Localisation",
    degreeLabel: "Diplôme",
    statsPublications: "Publications",
    statsHIndex: "H-index",
    statsProjects: "Projets de recherche",
    publicationsTitle: "Publications",
    publicationsRecent: "récentes",
    viewAll: "Voir toutes ({{count}})",
    viewLess: "Voir moins",
    pubSearchPlaceholder: "Rechercher par titre...",
    pubFilterAll: "Toutes",
    pubFilterRecent: "Récentes",
    pubFilterMostCited: "Plus citées",
    noMorePublications: "Pas d'autres publications.",
    loginTitle: "Connexion Chercheur",
    loginSubtitle: "Accédez à votre espace de recherche",
    rememberMe: "Se souvenir de moi",
    forgotPassword: "Mot de passe oublié ?",
    loginError: "Identifiants invalides ou erreur serveur.",
    heroTitle: "ScholarHub",
    heroText:
      "Gérez votre profil de recherche et connectez-vous avec la communauté scientifique.",
    feature1: "Innovation et Recherche",
    feature2: "Collaboration Mondiale",
    feature3: "Publications Scientifiques",
    manageResearchers: "Gestion des Chercheurs",
    searchResearchersPlaceholder: "Rechercher par nom, email ou domaine...",
    searchProfiles: "Rechercher un profil...",
    addResearcher: "Ajouter un chercheur",
    notSpecified: "Non spécifié",
    statusOnline: "En ligne",
    loadResearchersError: "Erreur lors du chargement des chercheurs",
    confirmDeleteResearcher: "Supprimer ce chercheur ?",
    deleteResearcherError: "Échec de la suppression. Veuillez réessayer.",
    tableHeaderName: "Nom",
    tableHeaderEmail: "Email",
    tableHeaderDomain: "Domaine",
    tableHeaderStatus: "Statut",
    selectAll: "Tout sélectionner",
    selectRow: "Sélectionner {{name}}",
    avatarAlt: "Photo de profil de {{name}}",
    editAction: "Modifier {{name}}",
    deleteAction: "Supprimer {{name}}",
    modalTitleEditNews: "Modifier l'actualité",
    dashboard: "Tableau de bord",
    cancelButton: "Annuler",
    updateError: "Erreur lors de la mise à jour",
    modalTitleEditProfile: "Modifier le profil",
    statusPlaceholder: "Statut",
    aboutPlaceholder: "À propos de moi...",
    noPhoto: "Aucune photo",
    changePhoto: "Changer",
    removePhoto: "Supprimer",
    importCV: "Importer CV",
    saving: "Enregistrement",
    userNotFound: "Utilisateur non trouvé ou non connecté",
    adminRole: "Administrateur",
    sideMenuAriaLabel: "Navigation latérale",
    closeMenu: "Fermer le menu",
    institutions: "Institutions",
    security: "Sécurité",
    publishedOn: "Publié le :",
    viewPdfBtn: "Voir le PDF",
    profile: "Profil",
    sortAsc: "▲",
    sortDesc: "▼",
    step1: "Changer mot de passe",
    step2: "Compléter profil",
    step3: "Sélectionner publications",
    stepLabel: "Étape {current} sur {total}",
    dateFormat: "dd MMMM yyyy",
    ResearchersTitle: "Chercheurs",
    aboutTitle: "À propos de ScholarHub",
    aboutSubtitle: "Portail de gestion des profils chercheurs",
    uploadPhoto: "chargerPhoto",
    orDragAndDrop: "ou glisser-déposer",
    missionTitle: "Notre Mission",
    missionItems: [
      "Centraliser et structurer les informations des chercheurs (profils, publications, événements)",
      "Faciliter la recherche et le partage d'informations scientifiques",
      "Faciliter les collaborations scientifiques interdisciplinaires",
      "Automatiser la mise à jour via sources externes (Scopus)",
    ],

    featuresTitle: "Fonctionnalités Clés",
    functionalTitle: "Fonctionnalités Principales",
    functionalItems: [
      "CRUD complet des profils et publications",
      "Import automatisé depuis Scopus",
      "Génération dynamique de CVthèques",
      "Alertes personnalisées pour appels à projets",
      "Recherche multicritères avec filtres dynamiques",
      "Tableau de bord avec statistiques temps réel",
      "Design responsive et accessible (WCAG 2.1)",
    ],
    securityTitle: "Sécurité & Conformité",
    securityItems: [
      "Authentification JWT sécurisée",
      "Chiffrement AES-256 des données sensibles",
      "Protection contre XSS/CSRF/SQL Injection",
      "Conformité RGPD stricte",
      "Gestion fine des permissions (3 rôles)",
      "Sauvegardes automatisées et chiffrées",
    ],

    architectureTitle: "Architecture Technique",
    architectureSections: [
      {
        id: "frontend",
        title: "Frontend",
        features: [
          "React 19 + Server Components",
          "Tailwind CSS 3.3 + Vite",
          "Figma pour le design",
        ],
      },
      {
        id: "backend",
        title: "Backend",
        features: [
          "Laravel 11 (PHP 8.3)",
          "API REST avec Sanctum/JWT",
          "Intégration Scopus API",
        ],
      },
      {
        id: "database",
        title: "Persistance",
        features: [
          "MySQL 8.2 Clusterisé",
          "Migrations Eloquent ORM",
          "Stockage S3 pour documents",
        ],
      },
    ],

    teamTitle: "Équipe du Projet",
    teamMembers: [
      {
        name: "Badreddine BENHILA",
        role: "Développeur Full-Stack",
        responsibility: "Interface utilisateur & UX",
      },
      {
        name: "Ouassim DERJA",
        role: "Développeur Full-Stack",
        responsibility: "Architecture backend & Sécurité",
      },
      {
        name: "Mr. Benamrane",
        role: "Encadrant Pédagogique",
        responsibility: "Supervision générale",
      },
      {
        name: "Mr. Mourdi",
        role: "Encadrant Technique",
        responsibility: "Validation architecture",
      },
    ],
    researcherImageAlt: "Chercheur en pleine activité",
    upcomingEvents: "Événements scientifiques à venir",
    eventsAnd: "Événements scientifiques à venir",
    conferenceTitle: "Conférence",
    recentPublications: "Publications Récentes",
    discoverLatestResearch: "Découvrez les dernières recherches",
    tryAgain: "Réessayer",
    noUpcomingEvents: "Aucun événement à venir",
    footerAboutTitle: "À propos",
    footerAboutText:
      "Le portail de gestion des profils des chercheurs vise à centraliser les publications scientifiques et à faciliter la collaboration interdisciplinaire entre chercheurs.",
    footerQuickLinksTitle: "Liens rapides",
    footerContactTitle: "Contact",
    footerFollowUsTitle: "Suivez-nous",
    footerAddress: "Sidi Bouzid, B.P. 4162, 46000 SAFI - MAROC -",
    footerEmail: "contact@portail-chercheurs.com",
    footerPhone: "+212 600 000 000",
    footerCopyright:
      "&copy; {year} Portail des Chercheurs. Tous droits réservés.",
    navHome: "Accueil",
    navResearchers: "Chercheurs",
    navNews: "Actualités",
    navPublications: "Publications",
    navAbout: "À propos",
    socialFacebook: "Facebook",
    socialTwitter: "Twitter",
    socialLinkedIn: "LinkedIn",
    featuredResearchers: "Chercheurs en Vedette",
    viewAllResearchers: "Voir tous les chercheurs",
    errorLoadingResearchers: "Erreur lors du chargement des chercheurs",
    contactTitle: "Contactez notre équipe",
    contactSubtitle: "Nous sommes là pour répondre à vos questions",
    contactInfoTitle: "Informations de contact",
    contactInfoDescription:
      "Notre équipe vous répondra dans les plus brefs délais.",
    sendMessageTitle: "Envoyer un message",
    subjectLabel: "Sujet",
    subjectPlaceholder: "Quel est l'objet de votre message ?",
    messageLabel: "Message",
    messagePlaceholder: "Décrivez votre demande en détails...",
    sendButton: "Envoyer le message",
    sending: "Envoi en cours...",
    viewMorePublications: "Voir Plus de Publications",
    successTitle: "Message envoyé avec succès !",
    successMessage:
      "Nous avons bien reçu votre message et vous répondrons rapidement.",
    errorTitle: "Erreur lors de l'envoi",
    errorMessage: "Une erreur est survenue. Veuillez réessayer plus tard.",
    responseTimeInfo: "Nous nous engageons à vous répondre dans les 24 heures.",
    computerScience: "Informatique",
    biology: "Biologie",
    physics: "Physique",
    featuredResearchersDescription:
      "Découvrez les chercheurs les plus actifs et leurs contributions récentes.",
    monthlyActivity: "Activité Mensuelle",
    publicationDistribution: "Répartition des Publications",
    monthJul: "Juil",
    monthAug: "Août",
    monthSep: "Sep",
    monthOct: "Oct",
    monthNov: "Nov",
    statComments: "Commentaires",
    totalComments: "Total des commentaires",
    averageComments: "Moyenne mensuelle",
    peakActivity: "Pic d'activité",
    commentTrend: "Evolution des commentaires",
    last6Months: "6 derniers mois",
    totalPublications: "Total des publications",
    thisMonth: "Ce mois",
    lastMonth: "Mois précédent",
    currentMonth: "Mois courant",
    monthlyAverage: "Moyenne mensuelle",
    publicationTrend: "Tendance des publications",
    unknownDiscipline: "Non spécifiée",
    myDashboard: "Mon tableau de bord",
    profileLoadingError: "Erreur lors du chargement de ton profil",
    monthlyComparison: "Comparaison mensuelle",
    makePublic: "Rendre publique",
    makePrivate: "Rendre privée",
    allYears: "Toutes les années",
    notifications: "Notifications",
    noNotifications: "Aucune notification",
    stayInformed: "Restez Informé",
    stayInformedDesc:
      "Recevez les dernières actualités de la recherche scientifique et les événements à venir directement dans votre boîte mail.",
    markAsRead: "Marquer comme lu",
    Admindashboard: "Tableau de bord administrateur",
    allDomains: "Toutes les disciplines",
    loadingResearcherStats: "Chargement de vos statistiques…",
    researcherDashboardTitle: "Votre tableau de bord",
    publicationsLabel: "Publications",
    followersLabel: "Abonnés",
    collaborationsLabel: "Collaborations",
    distributionByDiscipline: "Répartition des publications par discipline",
    performanceOfPublications: "Performances des publications",
    latestActivitiesTitle: "Dernières activités",
    lastPublicationTitle: "Dernière publication",
    recentCollaborationTitle: "Collaboration la plus récente",
    noActivityFallback: "Aucune activité",
    noCategory: "Non classé",
    noData: "Aucune donnée",
    skipStep: "Sauter l'étape",
    profilePhoto: "Photo de profil",
  },

  en: {
    home: "Home",
    researchers: "Researchers",
    publications: "Publications",
    news: "News",
    about: "About",
    contact: "Contact",
    login: "Login",
    logout: "Logout",
    myAccount: "My Account",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    switchLanguage: "Switch language",
    calendar: "Calendar",
    list: "List",
    next: "Next",
    previous: "Previous",
    today: "Today",
    month: "Month",
    week: "Week",
    day: "Day",
    events: "Events",
    showMore: "Show more",
    error404: "Page not found",
    pageNotFound: "Sorry, we couldn't find the page you're looking for.",
    backToHome: "Back to home",
    searchPublications: "Search publications...",
    filter: "Filter",
    year: "Year",
    domain: "Domain",
    activeResearchers: "Active Researchers",
    citations: "Citations",
    profileError: "Error retrieving profile",
    help: "Help",
    featuredResearchersDescription:
      "Discover the most active researchers and their recent contributions.",
    contactSupport: "Contact support",
    more: "more",
    loading: "Loading...",
    welcomeMessage: "Welcome, {name}}!",
    viewMorePublications: "View More Publications",
    stayInformedDesc:
      "Receive the latest scientific research news and upcoming events directly in your inbox.",
    appearance: "Appearance",
    lightTheme: "Light theme",
    darkTheme: "Dark theme",
    systemTheme: "System",
    french: "French",
    english: "English",
    save: "Save",
    close: "Close",
    back: "Back",
    share: "Share",
    comments: "Comments",
    downloadPDF: "Download PDF",
    abstract: "Abstract",
    name: "Name",
    department: "Department",
    homeTitle: "Facilitate Access to Research Profiles",
    homeSubtitle:
      "Easily find researcher information and their scientific work.",
    featuredResearchers: "Featured Researchers",
    pageNotFoundTitle: "Page not found",
    pageNotFoundDesc: "Sorry, we couldn’t find the page you’re looking for.",
    exploreResearchers: "Explore Researchers",
    learnMore: "Learn More",
    researchersCount: "Researchers",
    publicationsCount: "Publications",
    projectsCount: "Projects",
    countriesCount: "Countries",
    homeWelcomeTitle:
      "Welcome to the Researchers Portal [Page under development]",
    homeWelcomeText:
      "Access researcher profiles, discover their work, and explore possible collaborations.",
    abstractTitle: "Abstract",
    fullTextTitle: "Full Text",
    statsTitle: "Statistics",
    citationsLabel: "Citations",
    downloadsLabel: "Downloads",
    downloadPdfBtn: "Download PDF",
    viewCitationsBtn: "View Citations",
    relatedPubsTitle: "Related Publications",
    backBtnAria: "Go back",
    actualiteNotFoundTitle: "News Not Found",
    actualiteNotFoundDesc:
      "The requested news item does not exist or has been deleted",
    dateLabel: "On",
    categoryLabel: "Category",
    backButton: "Back",
    shareButton: "Share",
    commentsTitle: "Comments",
    addCommentPlaceholder: "Add a comment...",
    postCommentButton: "Post",
    filterButton: "Filter",
    filterByName: "Name",
    filterByDepartment: "Department",
    filterByPublications: "Publications",
    errorLoadingData: "Error loading data",
    noResults: "No results",
    closeButtonAria: "Close",
    agenda: "Agenda",
    adminNewsTitle: "News Management",
    addButton: "Add",
    filterAll: "All",
    filterFuture: "Upcoming",
    filterArchive: "Archived",
    tableHeaderTitle: "Title",
    tableHeaderLocation: "Location",
    tableHeaderDate: "Date",
    tableHeaderCategory: "Category",
    tableHeaderActions: "Actions",
    noNewsFound: "No news found.",
    confirmDelete: "Confirm deletion?",
    adminResearchersTitle: "Researchers Management",
    adminLoginTitle: "Administrator Login",
    emailLabel: "Email",
    emailPlaceholder: "admin@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    loginButton: "Log in",
    dashboardTitle: "Dashboard",
    searchProfiles: "Search a Profil...",
    createNewsTitle: "Create News",
    titrePlaceholder: "Title",
    locationPlaceholder: "Location",
    descriptionPlaceholder: "Description",
    categoryPlaceholder: "Category",
    creationSuccess: "News created successfully!",
    creationError: "Error creating news!",
    createResearcherTitle: "Create Researcher Account",
    firstNameLabel: "First Name",
    firstNamePlaceholder: "First Name",
    lastNameLabel: "Last Name",
    lastNamePlaceholder: "Last Name",
    createAccountButton: "Create Account",
    researcherCreationSuccess: "Researcher created successfully!",
    researcherCreationErrorPrefix: "Error creating researcher: ",
    unknownError: "Unknown error",
    changePasswordTitle: "Change Password",
    currentPasswordLabel: "Current Password",
    currentPasswordPlaceholder: "••••••••",
    newPasswordLabel: "New Password",
    newPasswordPlaceholder: "••••••••",
    confirmPasswordLabel: "Confirm New Password",
    confirmPasswordPlaceholder: "••••••••",
    passwordMismatch: "Passwords do not match.",
    passwordChangeSuccess: "Password changed successfully!",
    passwordChangeError: "An error occurred while changing the password.",
    completeProfileFormTitle: "Complete your profile",
    scopusIdPlaceholder: "Scopus ID",
    disciplinePlaceholder: "Discipline",
    submitButton: "Submit",
    statPublications: "Publications",
    statResearchers: "Researchers",
    statVisitors: "Visitors",
    chartTitle: "Researchers Statistics",
    chartLabelResearchers: "Researchers",
    monthDec: "Dec",
    monthJan: "Jan",
    monthFeb: "Feb",
    monthMar: "Mar",
    monthApr: "Apr",
    monthMay: "May",
    monthJun: "Jun",
    upcomingEventTitle: "Events",
    upcomingEventDesc: "Discover updates and prepare for the next event",
    viewMoreButton: "View more",
    statsLoadError: "Error loading statistics:",
    profileLoadError: "Unable to load profile.",
    universityLabel: "University",
    contactButton: "Contact",
    editButton: "Edit",
    infoTitle: "Information",
    locationLabel: "Location",
    degreeLabel: "Degree",
    statsHIndex: "H-index",
    statsProjects: "Research projects",
    publicationsTitle: "Publications",
    publicationsRecent: "recent",
    viewAll: "View all ({{count}})",
    viewLess: "View less",
    pubSearchPlaceholder: "Search by title...",
    pubFilterAll: "All",
    pubFilterRecent: "Recent",
    pubFilterMostCited: "Most cited",
    noMorePublications: "No more publications.",
    loginTitle: "Researcher Login",
    loginSubtitle: "Access your research workspace",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    loginError: "Invalid credentials or server error.",
    heroTitle: "ScholarHub",
    heroText:
      "Manage your research profile and connect with the scientific community.",
    feature1: "Innovation & Research",
    feature2: "Global Collaboration",
    feature3: "Scientific Publications",
    manageResearchers: "Researchers Management",
    searchResearchersPlaceholder: "Search by name, email or domain...",
    addResearcher: "Add Researcher",
    notSpecified: "Not specified",
    statusOnline: "Online",
    loadResearchersError: "Error loading researchers",
    confirmDeleteResearcher: "Delete this researcher?",
    deleteResearcherError: "Deletion failed. Please try again.",
    tableHeaderName: "Name",
    tableHeaderEmail: "Email",
    tableHeaderDomain: "Domain",
    tableHeaderStatus: "Status",
    selectAll: "Select all",
    selectRow: "Select {{name}}",
    avatarAlt: "{{name}}'s avatar",
    editAction: "Edit {{name}}",
    deleteAction: "Delete {{name}}",
    modalTitleEditNews: "Edit News",
    cancelButton: "Cancel",
    updateError: "Error updating news",
    modalTitleEditProfile: "Edit Profile",
    statusPlaceholder: "Status",
    aboutPlaceholder: "About me...",
    noPhoto: "No photo",
    changePhoto: "Change",
    removePhoto: "Remove",
    importCV: "Import CV",
    saving: "Saving",
    userNotFound: "User not found or not logged in",
    adminRole: "Administrator",
    adminDisciplineTitle: "Disciplines Management",
    sideMenuAriaLabel: "Side navigation",
    closeMenu: "Close menu",
    institutions: "Institutions",
    security: "Security",
    publishedOn: "Published on:",
    viewPdfBtn: "View PDF",
    profile: "Profile",
    sortAsc: "▲",
    sortDesc: "▼",
    step1: "Change Password",
    step2: "Complete Profile",
    step3: "Select Publications",
    stepLabel: "Step {current} of {total}",
    dateFormat: "dd MMMM yyyy",
    ResearchersTitle: "Resarchers",
    aboutTitle: "About ScholarHub",
    aboutSubtitle: "Researcher profile management portal",

    missionTitle: "Our Mission",
    missionItems: [
      "Centralize and structure researcher information (profiles, publications, events)",
      "Facilitate scientific information sharing",
      "Encourage interdisciplinary collaborations",
      "Automate updates via external sources (Scopus)",
    ],

    featuresTitle: "Key Features",
    functionalTitle: "Core Features",
    functionalItems: [
      "Full CRUD on profiles & publications",
      "Automated import from Scopus",
      "Dynamic CV library generation",
      "Custom alerts for calls for proposals",
      "Multi-criteria search with dynamic filters",
      "Real-time stats dashboard",
      "Responsive & accessible design (WCAG 2.1)",
    ],
    securityTitle: "Security & Compliance",
    securityItems: [
      "Secure JWT authentication",
      "AES-256 encryption for sensitive data",
      "Protection against XSS/CSRF/SQL Injection",
      "Strict GDPR compliance",
      "Granular permissions (3 roles)",
      "Automated encrypted backups",
    ],

    architectureTitle: "Technical Architecture",
    architectureSections: [
      {
        id: "frontend",
        title: "Frontend",
        features: [
          "React 19 + Server Components",
          "Tailwind CSS 3.3 + Vite",
          "Figma for design",
        ],
      },
      {
        id: "backend",
        title: "Backend",
        features: [
          "Laravel 11 (PHP 8.3)",
          "REST API with Sanctum/JWT",
          "Scopus API integration",
        ],
      },
      {
        id: "database",
        title: "Persistence",
        features: [
          "MySQL 8.2 Clustered",
          "Eloquent ORM migrations",
          "S3 storage for documents",
        ],
      },
    ],

    teamTitle: "Project Team",
    teamMembers: [
      {
        name: "Badreddine BENHILA",
        role: "Full-Stack Developer",
        responsibility: "UI & UX",
      },
      {
        name: "Ouassim DERJA",
        role: "Full-Stack Developer",
        responsibility: "Backend Architecture & Security",
      },
      {
        name: "Mr. Benamrane",
        role: "Educational Supervisor",
        responsibility: "Overall supervision",
      },
      {
        name: "Mr. Mourdi",
        role: "Technical Supervisor",
        responsibility: "Architecture validation",
      },
    ],

    upcomingEvents: "Upcoming Scientific Events",
    conferenceTitle: "Conference",
    recentPublications: "Recent publications",
    discoverLatestResearch: "Découvrez les dernières recherches",
    tryAgain: "Try again",
    noUpcomingEvents: "No upcoming events",
    footerAboutTitle: "About",
    footerAboutText:
      "The research profile management portal aims to centralize scientific publications and facilitate interdisciplinary collaboration between researchers.",
    footerQuickLinksTitle: "Quick Links",
    footerContactTitle: "Contact",
    footerFollowUsTitle: "Follow Us",
    footerAddress: "Sidi Bouzid, B.P. 4162, 46000 SAFI - MOROCCO -",
    footerEmail: "contact@portail-chercheurs.com",
    footerPhone: "+212 600 000 000",
    footerCopyright: "&copy; {year} Research Portal. All rights reserved.",
    navHome: "Home",
    navResearchers: "Researchers",
    navNews: "News",
    navPublications: "Publications",
    navAbout: "About",
    socialFacebook: "Facebook",
    socialTwitter: "Twitter",
    socialLinkedIn: "LinkedIn",
    featuredResearchers: "Featured Researchers",
    viewAllResearchers: "View All Researchers",
    errorLoadingResearchers: "Error loading researchers",
    contactTitle: "Contact our team",
    contactSubtitle: "We are here to answer your questions",
    contactInfoTitle: "Contact Information",
    contactInfoDescription:
      "Our team will get back to you as soon as possible.",
    sendMessageTitle: "Send a message",
    subjectLabel: "Subject",
    subjectPlaceholder: "What is the subject of your message?",
    messageLabel: "Message",
    messagePlaceholder: "Describe your request in detail...",
    sendButton: "Send message",
    sending: "Sending...",
    successTitle: "Message sent successfully!",
    successMessage:
      "We have received your message and will get back to you shortly.",
    errorTitle: "Error sending message",
    errorMessage: "An error occurred. Please try again later.",
    responseTimeInfo: "We are committed to responding within 24 hours.",
    computerScience: "Computer Science",
    biology: "Biology",
    physics: "Physics",

    monthlyActivity: "Monthly Activity",
    publicationDistribution: "Publication Distribution",
    monthJul: "Jul",
    monthAug: "Aug",
    monthSep: "Sep",
    monthOct: "Oct",
    monthNov: "Nov",
    statComments: "Comments",
    totalComments: "Total comments",
    averageComments: "Monthly average",
    peakActivity: "Peak activity",
    commentTrend: "Comments trend",
    last6Months: "Last 6 months",
    totalPublications: "Total publications",
    thisMonth: "This month",
    lastMonth: "Last month",
    currentMonth: "Current month",
    monthlyAverage: "Monthly average",
    publicationTrend: "Publication trend",
    unknownDiscipline: "Not specified",
    myDashboard: "My Dashboard",
    profileLoadingError: "Error loading your profile",
    monthlyComparison: "Monthly comparison",
    makePublic: "Make public",
    makePrivate: "Make private",
    allYears: "All years",
    notifications: "Notifications",
    noNotifications: "No notifications",
    markAsRead: "Mark as read",
    Admindashboard: "Admin Dashboard",
    allDomains: "All domains",
    loadingResearcherStats: "Loading your statistics…",
    researcherDashboardTitle: "Your Dashboard",
    publicationsLabel: "Publications",
    followersLabel: "Followers",
    collaborationsLabel: "Collaborations",
    distributionByDiscipline: "Publications by Discipline",
    performanceOfPublications: "Publication Performance",
    latestActivitiesTitle: "Latest Activities",
    lastPublicationTitle: "Last Publication",
    recentCollaborationTitle: "Most Recent Collaboration",
    noActivityFallback: "No activity",
    noCategory: "Uncategorized",
    noData: "No data",
  },
};
export const LanguageContext = createContext({
  language: "fr",
  t: (key) => key,
  switchLanguage: () => {},
  formatDate: () => {},
  formatNumber: () => {},
  availableLanguages: ["fr", "en"],
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("fr");
  const [fallbackLanguage] = useState("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") || "fr";
    setLanguage(savedLang);
    document.documentElement.lang = savedLang;
  }, []);

  // Fonction de traduction
  const t = (key, params = {}) => {
    let translation =
      translations[language]?.[key] ||
      translations[fallbackLanguage][key] ||
      key;
    Object.entries(params).forEach(([paramKey, value]) => {
      translation = translation.replace(`{${paramKey}}}`, value);
    });
    return translation;
  };

  // Changer la langue
  const switchLanguage = (newLang) => {
    if (!translations[newLang]) return;
    localStorage.setItem("language", newLang);
    setLanguage(newLang);
    document.documentElement.lang = newLang;
  };

  // Formatage sécurisé des dates
  const formatDate = (dateInput, options = {}) => {
    const date = new Date(dateInput);
    if (isNaN(date.getTime())) {
      return (
        translations[language]?.["dateNotAvailable"] ||
        translations[fallbackLanguage]?.["dateNotAvailable"] ||
        "–"
      );
    }
    try {
      return new Intl.DateTimeFormat(language, options).format(date);
    } catch {
      return new Intl.DateTimeFormat(fallbackLanguage, options).format(date);
    }
  };

  // Formatage sécurisé des nombres
  const formatNumber = (number, options = {}) => {
    try {
      return new Intl.NumberFormat(language, options).format(number);
    } catch {
      return new Intl.NumberFormat(fallbackLanguage, options).format(number);
    }
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        t,
        switchLanguage,
        formatDate,
        formatNumber,
        availableLanguages: Object.keys(translations),
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

// Export par défaut pour faciliter l'import
export default LanguageContext;
