import React, { createContext, useState, useEffect } from "react";

export const translations = {
  fr: {
    home: "Accueil",
    researchers: "Enseignants-chercheurs",
    publications: "Publications",
    news: "Actualités",
    about: "À propos",
    contact: "Contact",
    login: "Connexion",
    logout: "Déconnexion",
    myAccount: "Mon compte",
    settings: "Paramètres",
    language: "Langue",
    theme: "Thème",
    switchLanguage: "Changer la langue",
    calendar: "Calendrier",
    list: "Liste",
    next: "Suivant",
    previous: "Précédent",
    today: "Aujourd'hui",
    month: "Mois",
    week: "Semaine",
    day: "Jour",
    events: "Événements",
    showMore: "Voir plus",
    error404: "Page non trouvée",
    pageNotFound: "Désolé, nous n'avons pas trouvé la page que vous cherchez.",
    backToHome: "Retour à l'accueil",
    searchPublications: "Rechercher des publications...",
    filter: "Filtrer",
    year: "Année",
    domain: "Domaine",
    active: "Actifs",
    activeResearchers: "Enseignants-chercheurs Actifs",
    citations: "Citations",
    profileError: "Erreur de récupération du profil",
    help: "Aide",
    contactSupport: "Contacter le support",
    more: "plus",
    loading: "Chargement...",
    welcomeMessage: "Bienvenue, {name}} !",
    appearance: "Apparence",
    lightTheme: "Thème clair",
    darkTheme: "Thème sombre",
    systemTheme: "Système",
    french: "Français",
    english: "Anglais",
    save: "Sauvegarder",
    close: "Fermer",
    back: "Retour",
    share: "Partager",
    comments: "Commentaires",
    downloadPDF: "Télécharger le PDF",
    abstract: "Résumé",
    name: "Nom",
    department: "Département",
    homeTitle: "Facilitez l’Accès aux Profils de Recherche",
    homeSubtitle:
      "Trouvez facilement les informations des enseignants-chercheurs et leurs travaux scientifiques.",
    pageNotFoundTitle: "Page non trouvée",
    pageNotFoundDesc:
      "Désolé, nous n'avons pas trouvé la page que vous cherchez.",
    exploreResearchers: "Explorer les Enseignants-chercheurs",
    learnMore: "En savoir plus",
    researchersCount: "Enseignants-chercheurs",
    publicationsCount: "Publications",
    projectsCount: "Projets",
    countriesCount: "Pays",
    homeWelcomeTitle:
      "Bienvenue sur le Portail des Enseignants-chercheurs [Page en cours de développement]",
    homeWelcomeText:
      "Accédez aux profils des enseignants-chercheurs, découvrez leurs travaux et explorez les collaborations possibles.",
    abstractTitle: "Résumé",
    fullTextTitle: "Contenu Intégral",
    statsTitle: "Statistiques",
    citationsLabel: "Citations",
    downloadsLabel: "Téléchargements",
    downloadPdfBtn: "Télécharger le PDF",
    viewCitationsBtn: "Voir les citations",
    relatedPubsTitle: "Publications Associées",
    backBtnAria: "Retour",
    actualiteNotFoundTitle: "Actualité non trouvée",
    actualiteNotFoundDesc:
      "L'actualité demandée n'existe pas ou a été supprimée",
    dateLabel: "Le",
    categoryLabel: "Catégorie",
    backButton: "Retour",
    shareButton: "Partager",
    commentsTitle: "Commentaires",
    addCommentPlaceholder: "Ajouter un commentaire...",
    postCommentButton: "Publier",
    chercheursTitle: "Enseignants-chercheurs",
    filterButton: "Filtrer",
    filterByName: "Nom",
    filterByDepartment: "Département",
    filterByPublications: "Publications",
    errorLoadingData: "Erreur lors du chargement des données",
    noResults: "Aucun résultat",
    closeButtonAria: "Fermer",
    agenda: "Agenda",
    adminNewsTitle: "Gestion des Actualités",
    adminDisciplineTitle: "Gestion des Disciplines",
    addButton: "Ajouter",
    filterAll: "Toutes",
    filterFuture: "À venir",
    filterArchive: "Archivées",
    tableHeaderTitle: "Titre",
    tableHeaderLocation: "Localisation",
    tableHeaderDate: "Date",
    tableHeaderCategory: "Catégorie",
    tableHeaderActions: "Actions",
    noNewsFound: "Aucune actualité trouvée.",
    confirmDelete: "Confirmer la suppression ?",
    adminResearchersTitle: "Gestion des Enseignants-chercheurs",
    adminLoginTitle: "Authentification Administrateur",
    emailLabel: "Email",
    emailPlaceholder: "username@example.com",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "••••••••",
    confirmArchiveResearcher: "Voulez-vous vraiment archiver ce chercheur ?",
    confirmPermanentDeleteResearcher:
      "Voulez-vous vraiment supprimer définitivement ce chercheur ? Cette action est irréversible.",
    restoreResearcher: "Restaurer",
    confirmRestoreResearcher: "Voulez-vous vraiment restaurer ce chercheur ?",
    restoreError: "Erreur lors de la restauration du chercheur",
    archivedStatus: "Archivé",
    activeStatus: "Actif",
    loginButton: "Se connecter",
    archivedResearchers: "Chercheurs archivés",
    archived: "Archivés",
    dashboardTitle: "Tableau de bord",
    createNewsTitle: "Créer une actualité",
    titrePlaceholder: "Titre",
    locationPlaceholder: "Localisation",
    descriptionPlaceholder: "Description",
    categoryPlaceholder: "Catégorie",
    creationSuccess: "Actualité ajoutée avec succès !",
    creationError: "Erreur lors de l'ajout !",
    createResearcherTitle: "Créer un compte enseignant-chercheur",
    firstNameLabel: "Prénom",
    firstNamePlaceholder: "Prénom",
    lastNameLabel: "Nom",
    lastNamePlaceholder: "Nom",
    createAccountButton: "Créer le compte",
    researcherCreationSuccess: "Enseignant-chercheur créé avec succès !",
    researcherCreationErrorPrefix: "Erreur lors de la création : ",
    unknownError: "Erreur inconnue",
    changePasswordTitle: "Changer le mot de passe",
    currentPasswordLabel: "Mot de passe actuel",
    currentPasswordPlaceholder: "••••••••",
    newPasswordLabel: "Nouveau mot de passe",
    newPasswordPlaceholder: "••••••••",
    confirmPasswordLabel: "Confirmer le nouveau mot de passe",
    confirmPasswordPlaceholder: "••••••••",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    passwordChangeSuccess: "Mot de passe changé avec succès !",
    passwordChangeError:
      "Une erreur s'est produite lors du changement de mot de passe.",
    completeProfileFormTitle: "Complétez votre profil",
    scopusIdPlaceholder: "ID Scopus",
    disciplinePlaceholder: "Discipline",
    specialisationPlaceholder: "Spécialisation",
    submitButton: "Valider",
    statPublications: "Publications",
    statResearchers: "Enseignants-chercheurs",
    statCourses: "Cours",
    statVisitors: "Visiteurs",
    chartTitle: "Statistiques des enseignants-chercheurs",
    chartLabelResearchers: "Enseignants-chercheurs",
    monthDec: "Déc",
    monthJan: "Jan",
    monthFeb: "Fév",
    monthMar: "Mar",
    monthApr: "Avr",
    monthMay: "Mai",
    monthJun: "Juin",
    upcomingEventTitle: "Événements",
    upcomingEventDesc:
      "Découvrez les nouveautés et préparez-vous pour le prochain événement",
    viewMoreButton: "Voir plus",
    statsLoadError: "Erreur lors du chargement des statistiques :",
    profileLoadError: "Impossible de charger le profil.",
    universityLabel: "Université",
    contactButton: "Contacter",
    editButton: "Modifier",
    infoTitle: "Informations",
    locationLabel: "Localisation",
    degreeLabel: "Diplôme",
    statsPublications: "Publications",
    statsCitations: "Citations",
    statsCollaboration: "Collaborations",
    statsHIndex: "H-index",
    statsProjects: "Projets de recherche",
    publicationsTitle: "Publications",
    publicationsRecent: "récentes",
    viewAll: "Voir toutes ({count}})",
    viewLess: "Voir moins",
    pubSearchPlaceholder: "Rechercher par titre...",
    pubFilterAll: "Toutes",
    pubFilterRecent: "Récentes",
    pubFilterMostCited: "Plus citées",
    noMorePublications: "Pas de publications.",
    loginTitle: "Connexion Enseignant-chercheur",
    loginSubtitle: "Accédez à votre espace de recherche",
    rememberMe: "Se souvenir de moi",
    forgotPassword: "Mot de passe oublié ?",
    loginError: "Identifiants invalides ou erreur serveur.",
    heroTitle: "ScholarHub",
    heroText:
      "Gérez votre profil de recherche et connectez-vous avec la communauté scientifique.",
    feature1: "Innovation et Recherche",
    feature2: "Collaboration Mondiale",
    feature3: "Publications Scientifiques",
    manageResearchers: "Gestion des Enseignants-chercheurs",
    searchResearchersPlaceholder: "Rechercher par nom, email ou domaine...",
    searchProfiles: "Rechercher un profil...",
    addResearcher: "Ajouter un enseignant-chercheur",
    notSpecified: "Non spécifié",
    statusOnline: "En ligne",
    loadResearchersError:
      "Erreur lors du chargement des enseignants-chercheurs",
    confirmDeleteResearcher: "Supprimer cet enseignant-chercheur ?",
    deleteResearcherError: "Échec de la suppression. Veuillez réessayer.",
    tableHeaderName: "Nom",
    tableHeaderEmail: "Email",
    tableHeaderDomain: "Domaine",
    tableHeaderStatus: "Statut",
    selectAll: "Tout sélectionner",
    selectRow: "Sélectionner {{name}}",
    avatarAlt: "Photo de profil de {{name}}",
    editAction: "Modifier {{name}}",
    deleteAction: "Supprimer {{name}}",
    modalTitleEditNews: "Modifier l'actualité",
    dashboard: "Tableau de bord",
    cancelButton: "Annuler",
    updateError: "Erreur lors de la mise à jour",
    modalTitleEditProfile: "Modifier le profil",
    statusPlaceholder: "Statut",
    aboutPlaceholder: "À propos de moi...",
    noPhoto: "Aucune photo",
    changePhoto: "Changer",
    removePhoto: "Supprimer",
    importCV: "Importer CV",
    saving: "Enregistrement",
    userNotFound: "Utilisateur non trouvé ou non connecté",
    adminRole: "Administrateur",
    sideMenuAriaLabel: "Navigation latérale",
    closeMenu: "Fermer le menu",
    institutions: "Institutions",
    security: "Sécurité",
    publishedOn: "Publié le :",
    viewPdfBtn: "Voir le PDF",
    profile: "Profil",
    sortAsc: "▲",
    sortDesc: "▼",
    step1: "Changer mot de passe",
    step2: "Compléter profil",
    step3: "Sélectionner publications",
    stepLabel: "Étape {current} sur {total}",
    dateFormat: "dd MMMM yyyy",
    ResearchersTitle: "Enseignants-chercheurs",
    aboutTitle: "À propos de ScholarHub",
    aboutSubtitle: "Portail de gestion des profils enseignants-chercheurs",
    uploadPhoto: "chargerPhoto",
    orDragAndDrop: "ou glisser-déposer",
    missionTitle: "Notre Mission",
    missionItems: [
      "Centraliser et structurer les informations des enseignants-chercheurs (profils, publications, événements)",
      "Faciliter la recherche et le partage d'informations scientifiques",
      "Faciliter les collaborations scientifiques interdisciplinaires",
      "Automatiser la mise à jour via sources externes (Scopus)",
    ],

    featuresTitle: "Fonctionnalités Clés",
    functionalTitle: "Fonctionnalités Principales",
    functionalItems: [
      "CRUD complet des profils et publications",
      "Import automatisé depuis Scopus",
      "Génération dynamique de CVthèques",
      "Alertes personnalisées pour appels à projets",
      "Recherche multicritères avec filtres dynamiques",
      "Tableau de bord avec statistiques temps réel",
      "Design responsive et accessible (WCAG 2.1)",
    ],
    securityTitle: "Sécurité & Conformité",
    securityItems: [
      "Authentification JWT sécurisée",
      "Chiffrement AES-256 des données sensibles",
      "Protection contre XSS/CSRF/SQL Injection",
      "Conformité RGPD stricte",
      "Gestion fine des permissions (3 rôles)",
      "Sauvegardes automatisées et chiffrées",
    ],

    architectureTitle: "Architecture Technique",
    architectureSections: [
      {
        id: "frontend",
        title: "Frontend",
        features: [
          "React 19 + Server Components",
          "Tailwind CSS 3.3 + Vite",
          "Figma pour le design",
        ],
      },
      {
        id: "backend",
        title: "Backend",
        features: [
          "Laravel 11 (PHP 8.3)",
          "API REST avec Sanctum/JWT",
          "Intégration Scopus API",
        ],
      },
      {
        id: "database",
        title: "Persistance",
        features: [
          "MySQL 8.2 Clusterisé",
          "Migrations Eloquent ORM",
          "Stockage S3 pour documents",
        ],
      },
    ],

    teamTitle: "Équipe du Projet",
    teamMembers: [
      {
        name: "Badreddine BENHILA",
        role: "Développeur Full-Stack",
        responsibility: "Interface utilisateur & UX",
      },
      {
        name: "Ouassim DERJA",
        role: "Développeur Full-Stack",
        responsibility: "Architecture backend & Sécurité",
      },
      {
        name: "Mr. Benamrane",
        role: "Encadrant Pédagogique",
        responsibility: "Supervision générale",
      },
      {
        name: "Mr. Mourdi",
        role: "Encadrant Technique",
        responsibility: "Validation architecture",
      },
    ],
    researcherImageAlt: "enseignant-chercheur en pleine activité",
    upcomingEvents: "Événements scientifiques à venir",
    eventsAnd: "Événements scientifiques à venir",
    conferenceTitle: "Conférence",
    eventsAndConferences: "Événements et Conférences",
    recentPublications: "Publications Récentes",
    discoverLatestResearch: "Découvrez les dernières recherches",
    tryAgain: "Réessayer",
    noUpcomingEvents: "Aucun événement à venir",
    footerAboutTitle: "À propos",
    footerAboutText:
      "Le portail de gestion des profils des enseignants-chercheurs vise à centraliser les publications scientifiques et à faciliter la collaboration interdisciplinaire entre enseignants-chercheurs.",
    footerQuickLinksTitle: "Liens rapides",
    footerContactTitle: "Contact",
    footerFollowUsTitle: "Suivez-nous",
    footerAddress: "Sidi Bouzid, B.P. 4162, 46000 SAFI - MAROC -",
    footerEmail: "contact@portail-chercheurs.com",
    footerPhone: "+212 600 000 000",
    footerCopyright:
      "&copy; {year} Portail des enseignants-chercheurs. Tous droits réservés.",
    navHome: "Accueil",
    navResearchers: "Enseignants-chercheurs",
    navNews: "Actualités",
    navPublications: "Publications",
    navAbout: "À propos",
    socialFacebook: "Facebook",
    socialTwitter: "Twitter",
    socialLinkedIn: "LinkedIn",
    featuredResearchers: "Enseignants-chercheurs en Vedette",
    viewAllResearchers: "Voir tous les enseignants-chercheurs",
    errorLoadingResearchers:
      "Erreur lors du chargement des enseignants-chercheurs",
    contactTitle: "Contactez notre équipe",
    contactSubtitle: "Nous sommes là pour répondre à vos questions",
    contactInfoTitle: "Informations de contact",
    contactInfoDescription:
      "Notre équipe vous répondra dans les plus brefs délais.",
    sendMessageTitle: "Envoyer un message",
    subjectLabel: "Sujet",
    subjectPlaceholder: "Quel est l'objet de votre message ?",
    messageLabel: "Message",
    messagePlaceholder: "Décrivez votre demande en détails...",
    sendButton: "Envoyer le message",
    sending: "Envoi en cours...",
    viewMorePublications: "Voir Plus de Publications",
    successTitle: "Message envoyé avec succès !",
    successMessage:
      "Nous avons bien reçu votre message et vous répondrons rapidement.",
    errorTitle: "Erreur lors de l'envoi",
    errorMessage: "Une erreur est survenue. Veuillez réessayer plus tard.",
    responseTimeInfo: "Nous nous engageons à vous répondre dans les 24 heures.",
    computerScience: "Informatique",
    biology: "Biologie",
    physics: "Physique",
    featuredResearchersDescription:
      "Découvrez les enseignants-chercheurs les plus actifs et leurs contributions récentes.",
    monthlyActivity: "Activité Mensuelle",
    publicationDistribution: "Répartition des Publications",
    monthJul: "Juil",
    monthAug: "Août",
    monthSep: "Sep",
    monthOct: "Oct",
    monthNov: "Nov",
    statComments: "Commentaires",
    totalComments: "Total des commentaires",
    averageComments: "Moyenne mensuelle",
    peakActivity: "Pic d'activité",
    commentTrend: "Evolution des commentaires",
    last6Months: "6 derniers mois",
    totalPublications: "Total des publications",
    thisMonth: "Ce mois",
    lastMonth: "Mois précédent",
    currentMonth: "Mois courant",
    monthlyAverage: "Moyenne mensuelle",
    publicationTrend: "Tendance des publications",
    unknownDiscipline: "Non spécifiée",
    myDashboard: "Mon tableau de bord",
    profileLoadingError: "Erreur lors du chargement de ton profil",
    monthlyComparison: "Comparaison mensuelle",
    makePublic: "Rendre publique",
    makePrivate: "Rendre privée",
    allYears: "Toutes les années",
    notifications: "Notifications",
    noNotifications: "Aucune notification",
    stayInformed: "Restez Informé",
    stayInformedDesc:
      "Recevez les dernières actualités de la recherche scientifique et les événements à venir directement dans votre boîte mail.",
    markAsRead: "Marquer comme lu",
    Admindashboard: "Tableau de bord administrateur",
    allDomains: "Toutes les disciplines",
    loadingResearcherStats: "Chargement de vos statistiques…",
    researcherDashboardTitle: "Mon tableau de bord",
    publicationsLabel: "Publications",
    followersLabel: "Abonnés",
    collaborationsLabel: "Collaborations",
    distributionByDiscipline: "Répartition des publications par discipline",
    performanceOfPublications: "Performances des publications",
    latestActivitiesTitle: "Dernières activités",
    lastPublicationTitle: "Dernière publication",
    recentCollaborationTitle: "Collaboration la plus récente",
    noActivityFallback: "Aucune activité",
    noCategory: "Non classé",
    noData: "Aucune donnée",
    skipStep: "Sauter l'étape",
    profilePhoto: "Photo de profil",
    myCourses: "Mes cours",
    mySubjects: "Mes matières",
    mySubjects: "Mes Matières",
    addSubject: "Ajouter une matière",
    cancel: "Annuler",
    errorFetchingSubjects: "Erreur de chargement des matières",
    errorAttachingSubject: "Erreur lors de l'ajout de la matière",
    errorDetachingSubject: "Erreur lors de la suppression de la matière",
    errorRefreshingSubjects: "Erreur de rechargement des matières",
    errorOccurredAttaching:
      "Une erreur est survenue lors de l'ajout de la matière",
    errorOccurredDetaching:
      "Une erreur est survenue lors de la suppression de la matière",
    addSubject: "Ajouter une matière",
    selectSubject: "Sélectionnez une matière",
    chooseSubjectPlaceholder: "-- Choisir une matière --",
    selectSubjectError: "Veuillez sélectionner une matière",
    alreadyAttachedError: "Cette matière est déjà associée",
    add: "Ajouter",
    noSubjectsTitle: "Aucune matière associée",
    noSubjectsMessage: "Commencez par ajouter une matière que vous enseignez",
    remove: "Retirer",
    confirmDetachMessage:
      'Êtes-vous sûr de vouloir retirer la matière "{{name}}" ?\n\nCette action est irréversible.',
    newCourse: "Nouveau cours",
    noCoursesFound: "Aucun cours trouvé",
    tryChangeFiltersOrCreate:
      "Essayez de modifier vos filtres ou créez un nouveau cours",
    errorLoadingCourses: "Erreur de chargement des cours :",
    invalidCourseId: "ID de cours invalide :",
    confirmDeleteCourse: "Supprimer ce cours définitivement ?",
    errorDeletingCourse: "Erreur de suppression :",
    unspecified: "Non spécifié",
    viewDetails: "Voir détails",
    edit: "Modifier",
    delete: "Supprimer",
    errorDeleteCourseMsg: "Échec de la suppression : {{message}}",
    editCourse: "Modifier le cours",
    newCourse: "Nouveau cours",
    errorFetchingSubjects: "Erreur lors de la récupération des matières :",
    errorFetchingCourse: "Erreur lors de la récupération du cours :",
    labelTitle: "Titre",
    labelDescription: "Description",
    labelDate: "Date de publication",
    labelSubject: "Matière",
    chooseSubjectPlaceholder: "-- Sélectionner une matière --",
    labelFile: "Fichier",
    optional: "(Laisser vide pour conserver le fichier actuel)",
    currentFile: "Fichier actuel : {{name}}",
    fileHelp: "Formats acceptés : PDF (max 10 MB)",
    errorTitleRequired: "Le titre est requis",
    errorDescRequired: "La description est requise",
    errorSelectSubject: "Veuillez sélectionner une matière",
    errorFileRequired: "Un fichier PDF est requis",
    errorFileType: "Le fichier doit être au format PDF",
    errorFileSize: "Le fichier ne doit pas dépasser 10 MB",
    errorOccurred: "Une erreur est survenue",
    cancel: "Annuler",
    updateCourse: "Mettre à jour",
    createCourse: "Créer le cours",
    updating: "Mise à jour…",
    creating: "Création…",
    searchLabel: "Recherche",
    searchPlaceholder: "Rechercher un cours...",
    subjectLabel: "Matière",
    allSubjectsOption: "Toutes les matières",
    resetFilters: "Réinitialiser",
    myCourses: "Mes Cours",
    newCourse: "Nouveau cours",
    searchLabel: "Rechercher",
    searchPlaceholder: "Rechercher un cours...",
    filterBySubject: "Filtrer par matière",
    allSubjectsOption: "Toutes les matières",
    resetFilters: "Réinitialiser les filtres",
    tryChangeFilters: "Essayez de modifier vos critères de recherche",
    errorFetchingCourses: "Erreur lors de la récupération des cours :",
    loadingStats: "Chargement des statistiques...",
    errorStatus: "Erreur",
    errorLoading: "Erreur de chargement",
    statsHeader: "Statistiques des Disciplines",
    statsSubheader: "Analyse des publications et citations par domaine",
    publicationsLabel: "Publications",
    citationsLabel: "Citations",
    barChartTitle: "Comparatif Publications/Citations par Discipline",
    doughnutChartTitle: "Répartition des Publications",
    axisTotal: "Nombre total",
    colDiscipline: "Discipline",
    colPublications: "Publications",
    colCitations: "Citations",
    noData: "Aucune donnée disponible",
    errorStatus: "Erreur",
    errorLoading: "Erreur de chargement",
    loadingPedStats: "Chargement des statistiques pédagogiques…",
    pedStatsTitle: "Statistiques Pédagogiques",
    pedStatsSubtitle: "Analyse des cours et matières enseignées",
    totalSubjects: "Matières",
    totalCourses: "Cours",
    activeTeachers: " enseignants-chercheurs actifs",
    subjects: "Total des matières enseignées",
    courses: "Total des cours publiés",
    teachers: " enseignants-chercheurs ayant publié au moins un cours",
    topSubjects: "Top 10 des matières",
    distributionBySubject: "Répartition par matière",
    topTeachers: "Top 10 des enseignants-chercheurs",
    monthlyTrend: "Évolution par mois",
    subjectsDetail: "Détail des matières",
    teachersDetail: "Détail des enseignants-chercheurs",
    subject: "Matière",
    courses: "Cours",
    percentage: "Pourcentage",
    teacher: "enseignant-chercheur",
    publishedCourses: "Cours publiés",
    addDiscipline: "Ajouter une discipline",
    disciplineNamePlaceholder: "Nom de la discipline",
    cancel: "Annuler",
    add: "Ajouter",
    adding: "Ajout en cours",
    disciplineAddedSuccess: "Discipline ajoutée avec succès",
    disciplineAddError: "Erreur lors de l'ajout de la discipline",
    confirmRemoveDiscipline:
      "Êtes-vous sûr de vouloir détacher cette discipline de la publication ?",
    disciplineRemovedSuccess: "Discipline détachée avec succès",
    disciplineRemoveError: "Erreur lors du détachement de la discipline",
    locale: "fr-FR",
    allCoursesTitle: "Tous les cours disponibles",
    allCoursesSubtitle: "Explorez l'ensemble des ressources pédagogiques",
    loadingCourses: "Chargement des cours…",
    errorLoadingCourses: "Erreur lors du chargement des cours.",
    tryChangingFilters: "Essayez de modifier vos filtres.",
    retryButton: "Réessayer",
    filterCoursesLabel: "Filtrer les cours",
    coursesFound: "{count}} cours trouvé",
    coursesFoundWithTotal: " {found}} sur {total}}",
    resetFilters: "Réinitialiser les filtres",
    noCoursesAvailable: "Aucun cours disponible",
    noCoursesYet: "Aucun cours n'a été publié pour le moment.",
    noCoursesMatch: "Aucun cours ne correspond à vos critères",
    subjectUnspecified: "Non spécifié",
    noDescription: "Aucune description disponible.",
    attachedFile: "Fichier attaché",
    download: "Télécharger",
    noFilePreview: "Aucun document à prévisualiser pour ce cours.",
    instructorByLabel: "Par {first}} {last}}",
    publishedOnLabel: "Publié le {date}}",
    saveButton: "Enregistrer",
    createNewSubject: "Créer une nouvelle matière",
    subjectNamePlaceholder: "Entrez le nom de la matière",
    createAndAttach: "Créer et attacher",
    createNew: "Créer nouvelle",
    errorCreatingSubject: "Erreur lors de la création de la matière",
    subjectNameRequired: "Veuillez entrer un nom pour la matière",
    errorOccurredCreating: "Une erreur est survenue lors de la création",
    subjectsTaught: "Matières enseignées",
    selectExistingDiscipline: "Sélectionnez une discipline",
    selectOption: "Choisissez une discipline",
    loading: "Chargement",
    errorLoadingDisciplines: "Erreur lors du chargement des disciplines",
    disciplineAddedSuccess: "Discipline ajoutée avec succès",
    disciplineAlreadyAttached:
      "Cette discipline est déjà associée à la publication",
    disciplineAddError: "Erreur lors de l'ajout de la discipline",
    confirmRemoveDiscipline:
      "Êtes-vous sûr de vouloir retirer cette discipline ?",
    disciplineRemovedSuccess: "Discipline retirée avec succès",
    disciplineRemoveError: "Erreur lors de la suppression de la discipline",
    adding: "Ajout en cours",
    avgCitations: "Citations moyennes",
    aboutUsTitle: "À propos de nous",
    aboutUsDescription:
      "Nous sommes une équipe passionnée dédiée à fournir des solutions innovantes et sur mesure pour nos clients. Avec des années d'expérience et une approche centrée sur l'humain, nous transformons les idées en réalité numérique tout en garantissant qualité et satisfaction.",
    learnMoreButton: "En savoir plus",
    viewMorePublications: "Voir Plus de Publications",
    noPublicationsFound: "Aucune publication trouvée",
    pedagogy: "Pédagogie",
  },
  ///////////////////////////////////////////////////////////////////////////////////////////////////////
  en: {
    home: "Home",
    researchers: "teachers-researchers",
    publications: "Publications",
    news: "News",
    about: "About",
    contact: "Contact",
    login: "Login",
    logout: "Logout",
    myAccount: "My Account",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    switchLanguage: "Switch language",
    calendar: "Calendar",
    list: "List",
    next: "Next",
    previous: "Previous",
    today: "Today",
    month: "Month",
    week: "Week",
    day: "Day",
    events: "Events",
    eventsAndConferences: "Events And Conferences",
    archived: "Archived",
    showMore: "Show more",
    error404: "Page not found",
    pageNotFound: "Sorry, we couldn't find the page you're looking for.",
    backToHome: "Back to home",
    searchPublications: "Search publications...",
    filter: "Filter",
    year: "Year",
    domain: "Domain",
    active: "Active",

    activeResearchers: "Active teachers-researchers",
    citations: "Citations",
    profileError: "Error retrieving profile",
    help: "Help",
    featuredResearchersDescription:
      "Discover the most active teachers-researchers and their recent contributions.",
    contactSupport: "Contact support",
    more: "more",
    loading: "Loading...",
    welcomeMessage: "Welcome, {name}}!",
    viewMorePublications: "View More Publications",
    stayInformed: "Stay Informed",
    stayInformedDesc:
      "Receive the latest scientific research news and upcoming events directly in your inbox.",
    appearance: "Appearance",
    lightTheme: "Light theme",
    darkTheme: "Dark theme",
    systemTheme: "System",
    french: "French",
    english: "English",
    save: "Save",
    close: "Close",
    back: "Back",
    share: "Share",
    comments: "Comments",
    downloadPDF: "Download PDF",
    abstract: "Abstract",
    name: "Name",
    department: "Department",
    homeTitle: "Facilitate Access to Research Profiles",
    homeSubtitle:
      "Easily find teachers-researchers information and their scientific work.",
    featuredResearchers: "Featured teachers-researchers",
    pageNotFoundTitle: "Page not found",
    pageNotFoundDesc: "Sorry, we couldn’t find the page you’re looking for.",
    exploreResearchers: "Explore teachers-researchers",
    learnMore: "Learn More",
    researchersCount: "teachers-researchers",
    publicationsCount: "Publications",
    projectsCount: "Projects",
    countriesCount: "Countries",
    homeWelcomeTitle:
      "Welcome to the teachers-researchers Portal [Page under development]",
    homeWelcomeText:
      "Access teachers-researchers profiles, discover their work, and explore possible collaborations.",
    abstractTitle: "Abstract",
    fullTextTitle: "Full Text",
    statsTitle: "Statistics",
    citationsLabel: "Citations",
    downloadsLabel: "Downloads",
    downloadPdfBtn: "Download PDF",
    viewCitationsBtn: "View Citations",
    relatedPubsTitle: "Related Publications",
    backBtnAria: "Go back",
    actualiteNotFoundTitle: "News Not Found",
    actualiteNotFoundDesc:
      "The requested news item does not exist or has been deleted",
    dateLabel: "On",
    categoryLabel: "Category",
    backButton: "Back",
    shareButton: "Share",
    commentsTitle: "Comments",
    addCommentPlaceholder: "Add a comment...",
    postCommentButton: "Post",
    filterButton: "Filter",
    filterByName: "Name",
    filterByDepartment: "Department",
    filterByPublications: "Publications",
    errorLoadingData: "Error loading data",
    noResults: "No results",
    closeButtonAria: "Close",
    agenda: "Agenda",
    adminNewsTitle: "News Management",
    addButton: "Add",
    filterAll: "All",
    filterFuture: "Upcoming",
    filterArchive: "Archived",
    tableHeaderTitle: "Title",
    tableHeaderLocation: "Location",
    tableHeaderDate: "Date",
    tableHeaderCategory: "Category",
    tableHeaderActions: "Actions",
    noNewsFound: "No news found.",
    confirmDelete: "Confirm deletion?",
    adminResearchersTitle: "Teachers-Researchers Management",
    adminLoginTitle: "Administrator Login",
    emailLabel: "Email",
    emailPlaceholder: "username@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    loginButton: "Log in",
    dashboardTitle: "Dashboard",
    searchProfiles: "Search a Profil...",
    createNewsTitle: "Create News",
    titrePlaceholder: "Title",
    locationPlaceholder: "Location",
    descriptionPlaceholder: "Description",
    categoryPlaceholder: "Category",
    creationSuccess: "News created successfully!",
    creationError: "Error creating news!",
    createResearcherTitle: "Create Teacher-Researcher Account",
    firstNameLabel: "First Name",
    firstNamePlaceholder: "First Name",
    lastNameLabel: "Last Name",
    lastNamePlaceholder: "Last Name",
    createAccountButton: "Create Account",
    researcherCreationSuccess: "Teacher-Researcher created successfully!",
    researcherCreationErrorPrefix: "Error creating teacher-Researcher: ",
    unknownError: "Unknown error",
    changePasswordTitle: "Change Password",
    currentPasswordLabel: "Current Password",
    currentPasswordPlaceholder: "••••••••",
    newPasswordLabel: "New Password",
    newPasswordPlaceholder: "••••••••",
    confirmPasswordLabel: "Confirm New Password",
    confirmPasswordPlaceholder: "••••••••",
    passwordMismatch: "Passwords do not match.",
    passwordChangeSuccess: "Password changed successfully!",
    passwordChangeError: "An error occurred while changing the password.",
    completeProfileFormTitle: "Complete your profile",
    scopusIdPlaceholder: "Scopus ID",
    disciplinePlaceholder: "Discipline",
    specialisationPlaceholder: "Specialization",
    submitButton: "Submit",
    statPublications: "Publications",
    statResearchers: "Teachers-Researchers",
    statCourses: "Courses",
    statVisitors: "Visitors",
    chartTitle: "Teachers-Researchers Statistics",
    chartLabelResearchers: "Teachers-Researchers",
    monthDec: "Dec",
    monthJan: "Jan",
    monthFeb: "Feb",
    monthMar: "Mar",
    monthApr: "Apr",
    monthMay: "May",
    monthJun: "Jun",
    upcomingEventTitle: "Events",
    upcomingEventDesc: "Discover updates and prepare for the next event",
    viewMoreButton: "View more",
    statsLoadError: "Error loading statistics:",
    profileLoadError: "Unable to load profile.",
    universityLabel: "University",
    contactButton: "Contact",
    editButton: "Edit",
    infoTitle: "Information",
    locationLabel: "Location",
    degreeLabel: "Degree",
    statsHIndex: "H-index",
    statsProjects: "Research projects",
    publicationsTitle: "Publications",
    publicationsRecent: "recent",
    viewAll: "View all ({{count}})",
    viewLess: "View less",
    pubSearchPlaceholder: "Search by title...",
    pubFilterAll: "All",
    pubFilterRecent: "Recent",
    pubFilterMostCited: "Most cited",
    noMorePublications: "No publications.",
    loginTitle: "Teacher-Researcher Login",
    loginSubtitle: "Access your research workspace",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    loginError: "Invalid credentials or server error.",
    heroTitle: "ScholarHub",
    heroText:
      "Manage your research profile and connect with the scientific community.",
    feature1: "Innovation & Research",
    feature2: "Global Collaboration",
    feature3: "Scientific Publications",
    manageResearchers: "Teachers-Researchers Management",
    searchResearchersPlaceholder: "Search by name, email or domain...",
    addResearcher: "Add Teacher-Researcher",
    notSpecified: "Not specified",
    statusOnline: "Online",
    loadResearchersError: "Error loading teachers-researchers",
    confirmDeleteResearcher: "Delete this teacher-researcher?",
    deleteResearcherError: "Deletion failed. Please try again.",
    tableHeaderName: "Name",
    tableHeaderEmail: "Email",
    tableHeaderDomain: "Domain",
    tableHeaderStatus: "Status",
    selectAll: "Select all",
    selectRow: "Select {{name}}",
    avatarAlt: "{{name}}'s avatar",
    editAction: "Edit {{name}}",
    deleteAction: "Delete {{name}}",
    modalTitleEditNews: "Edit News",
    cancelButton: "Cancel",
    updateError: "Error updating news",
    modalTitleEditProfile: "Edit Profile",
    statusPlaceholder: "Status",
    aboutPlaceholder: "About me...",
    noPhoto: "No photo",
    changePhoto: "Change",
    removePhoto: "Remove",
    importCV: "Import CV",
    saving: "Saving",
    userNotFound: "User not found or not logged in",
    adminRole: "Administrator",
    adminDisciplineTitle: "Disciplines Management",
    sideMenuAriaLabel: "Side navigation",
    closeMenu: "Close menu",
    institutions: "Institutions",
    security: "Security",
    publishedOn: "Published on:",
    viewPdfBtn: "View PDF",
    profile: "Profile",
    sortAsc: "▲",
    sortDesc: "▼",
    step1: "Change Password",
    step2: "Complete Profile",
    step3: "Select Publications",
    stepLabel: "Step {current} of {total}",
    dateFormat: "dd MMMM yyyy",
    ResearchersTitle: "Teachers-Researchers",
    aboutTitle: "About ScholarHub",
    aboutSubtitle: "Teachers-Researchers profile management portal",

    missionTitle: "Our Mission",
    missionItems: [
      "Centralize and structure teachers-researchers information (profiles, publications, events)",
      "Facilitate scientific information sharing",
      "Encourage interdisciplinary collaborations",
      "Automate updates via external sources (Scopus)",
    ],

    featuresTitle: "Key Features",
    functionalTitle: "Core Features",
    functionalItems: [
      "Full CRUD on profiles & publications",
      "Automated import from Scopus",
      "Dynamic CV library generation",
      "Custom alerts for calls for proposals",
      "Multi-criteria search with dynamic filters",
      "Real-time stats dashboard",
      "Responsive & accessible design (WCAG 2.1)",
    ],
    securityTitle: "Security & Compliance",
    securityItems: [
      "Secure JWT authentication",
      "AES-256 encryption for sensitive data",
      "Protection against XSS/CSRF/SQL Injection",
      "Strict GDPR compliance",
      "Granular permissions (3 roles)",
      "Automated encrypted backups",
    ],

    architectureTitle: "Technical Architecture",
    architectureSections: [
      {
        id: "frontend",
        title: "Frontend",
        features: [
          "React 19 + Server Components",
          "Tailwind CSS 3.3 + Vite",
          "Figma for design",
        ],
      },
      {
        id: "backend",
        title: "Backend",
        features: [
          "Laravel 11 (PHP 8.3)",
          "REST API with Sanctum/JWT",
          "Scopus API integration",
        ],
      },
      {
        id: "database",
        title: "Persistence",
        features: [
          "MySQL 8.2 Clustered",
          "Eloquent ORM migrations",
          "S3 storage for documents",
        ],
      },
    ],

    teamTitle: "Project Team",
    teamMembers: [
      {
        name: "Badreddine BENHILA",
        role: "Full-Stack Developer",
        responsibility: "UI & UX",
      },
      {
        name: "Ouassim DERJA",
        role: "Full-Stack Developer",
        responsibility: "Backend Architecture & Security",
      },
      {
        name: "Mr. Benamrane",
        role: "Educational Supervisor",
        responsibility: "Overall supervision",
      },
      {
        name: "Mr. Mourdi",
        role: "Technical Supervisor",
        responsibility: "Architecture validation",
      },
    ],

    upcomingEvents: "Upcoming Scientific Events",
    conferenceTitle: "Conference",
    recentPublications: "Recent publications",
    discoverLatestResearch: "Découvrez les dernières recherches",
    tryAgain: "Try again",
    noUpcomingEvents: "No upcoming events",
    footerAboutTitle: "About",
    footerAboutText:
      "The research profile management portal aims to centralize scientific publications and facilitate interdisciplinary collaboration between researchers.",
    footerQuickLinksTitle: "Quick Links",
    footerContactTitle: "Contact",
    footerFollowUsTitle: "Follow Us",
    footerAddress: "Sidi Bouzid, B.P. 4162, 46000 SAFI - MOROCCO -",
    footerEmail: "contact@portail-chercheurs.com",
    footerPhone: "+212 600 000 000",
    footerCopyright: "&copy; {year} Research Portal. All rights reserved.",
    navHome: "Home",
    navResearchers: "Teachers-Researchers",
    navNews: "News",
    navPublications: "Publications",
    navAbout: "About",
    socialFacebook: "Facebook",
    socialTwitter: "Twitter",
    socialLinkedIn: "LinkedIn",
    viewAllResearchers: "View All teachers-researchers",
    errorLoadingResearchers: "Error loading teachers-researchers",
    contactTitle: "Contact our team",
    contactSubtitle: "We are here to answer your questions",
    contactInfoTitle: "Contact Information",
    contactInfoDescription:
      "Our team will get back to you as soon as possible.",
    sendMessageTitle: "Send a message",
    subjectLabel: "Subject",
    subjectPlaceholder: "What is the subject of your message?",
    messageLabel: "Message",
    messagePlaceholder: "Describe your request in detail...",
    sendButton: "Send message",
    sending: "Sending...",
    successTitle: "Message sent successfully!",
    successMessage:
      "We have received your message and will get back to you shortly.",
    errorTitle: "Error sending message",
    errorMessage: "An error occurred. Please try again later.",
    responseTimeInfo: "We are committed to responding within 24 hours.",
    computerScience: "Computer Science",
    biology: "Biology",
    physics: "Physics",

    monthlyActivity: "Monthly Activity",
    publicationDistribution: "Publication Distribution",
    monthJul: "Jul",
    monthAug: "Aug",
    monthSep: "Sep",
    monthOct: "Oct",
    monthNov: "Nov",
    statComments: "Comments",
    totalComments: "Total comments",
    averageComments: "Monthly average",
    peakActivity: "Peak activity",
    commentTrend: "Comments trend",
    last6Months: "Last 6 months",
    totalPublications: "Total publications",
    thisMonth: "This month",
    lastMonth: "Last month",
    currentMonth: "Current month",
    monthlyAverage: "Monthly average",
    publicationTrend: "Publication trend",
    unknownDiscipline: "Not specified",
    myDashboard: "My Dashboard",
    profileLoadingError: "Error loading your profile",
    monthlyComparison: "Monthly comparison",
    makePublic: "Make public",
    makePrivate: "Make private",
    allYears: "All years",
    notifications: "Notifications",
    noNotifications: "No notifications",
    markAsRead: "Mark as read",
    Admindashboard: "Admin Dashboard",
    allDomains: "All domains",
    loadingResearcherStats: "Loading your statistics…",
    researcherDashboardTitle: "Our Dashboard",
    publicationsLabel: "Publications",
    followersLabel: "Followers",
    collaborationsLabel: "Collaborations",
    distributionByDiscipline: "Publications by Discipline",
    performanceOfPublications: "Publication Performance",
    latestActivitiesTitle: "Latest Activities",
    lastPublicationTitle: "Last Publication",
    recentCollaborationTitle: "Most Recent Collaboration",
    noActivityFallback: "No activity",
    noCategory: "Uncategorized",
    noData: "No data",
    myCourses: "My Courses",
    mySubjects: "My Subjects",
    addSubject: "Add Subject",
    cancel: "Cancel",
    errorFetchingSubjects: "Error fetching subjects",
    errorAttachingSubject: "Error attaching subject",
    errorDetachingSubject: "Error detaching subject",
    errorRefreshingSubjects: "Error refreshing subjects",
    errorOccurredAttaching: "An error occurred while attaching the subject",
    errorOccurredDetaching: "An error occurred while detaching the subject",
    addSubject: "Add Subject",
    selectSubject: "Select Subject",
    chooseSubjectPlaceholder: "-- Choose a subject --",
    selectSubjectError: "Please select a subject",
    alreadyAttachedError: "This subject is already attached",
    add: "Add",
    noSubjectsTitle: "No subjects attached",
    noSubjectsMessage: "Start by adding a subject you teach",
    remove: "Remove",
    confirmDetachMessage:
      'Are you sure you want to remove the subject "{{name}}"?\n\nThis action is irreversible.',
    newCourse: "New Course",
    noCoursesFound: "No Courses Found",
    tryChangeFiltersOrCreate:
      "Try changing your filters or create a new course",
    errorLoadingCourses: "Error loading courses:",
    invalidCourseId: "Invalid course ID:",
    confirmDeleteCourse: "Confirm delete course:",
    errorDeletingCourse: "Error deleting course:",
    unspecified: "Non spécifié",
    viewDetails: "Voir détails",
    edit: "Modifier",
    delete: "Supprimer",
    errorDeleteCourseMsg: "Error deleting course: {{message}}",
    editCourse: "Modifier le cours",
    newCourse: "Nouveau cours",
    errorFetchingSubjects: "Erreur lors de la récupération des matières :",
    errorFetchingCourse: "Erreur lors de la récupération du cours :",
    labelTitle: "Title",
    labelDescription: "Description",
    labelDate: "Date",
    labelSubject: "Subject",
    chooseSubjectPlaceholder: "-- Choose a subject --",
    labelFile: "File",
    optional: "(Leave empty to keep current file)",
    currentFile: "Current file: {{name}}",
    fileHelp: "Accepted formats: PDF (max 10 MB)",
    errorTitleRequired: "Title is required",
    errorDescRequired: "Description is required",
    errorSelectSubject: "Please select a subject",
    errorFileRequired: "A PDF file is required",
    errorFileType: "File must be in PDF format",
    errorFileSize: "File must not exceed 10 MB",
    errorOccurred: "An error occurred",
    cancel: "Cancel",
    updateCourse: "Update Course",
    createCourse: "Create Course",
    updating: "Updating...",
    creating: "Creating...",
    searchLabel: "Search",
    searchPlaceholder: "Search courses...",
    subjectLabel: "Subject",
    allSubjectsOption: "All subjects",
    resetFilters: "Reset filters",
    myCourses: "My Courses",
    newCourse: "New Course",
    searchLabel: "Search",
    searchPlaceholder: "Search courses...",
    filterBySubject: "Filter by subject",
    allSubjectsOption: "All subjects",
    resetFilters: "Reset filters",
    tryChangeFilters: "Try changing your search criteria",
    errorFetchingCourses: "Error fetching courses:",
    loadingStats: "Loading statistics…",
    errorStatus: "Error",
    errorLoading: "Loading error",
    statsHeader: "Disciplines Statistics",
    statsSubheader: "Analysis of publications and citations by field",
    publicationsLabel: "Publications",
    citationsLabel: "Citations",
    barChartTitle: "Publications/Citations Comparison by Discipline",
    doughnutChartTitle: "Publication Distribution",
    axisTotal: "Total count",
    colDiscipline: "Discipline",
    colPublications: "Publications",
    colCitations: "Citations",
    noData: "No data available",
    errorStatus: "Error",
    errorLoading: "Loading error",
    loadingPedStats: "Loading pedagogical statistics…",
    pedStatsTitle: "Pedagogical Statistics",
    pedStatsSubtitle: "Analysis of courses and taught subjects",
    totalSubjects: "Subjects",
    totalCourses: "Courses",
    activeTeachers: "Teachers-Researchers actifs",
    subjects: "Total taught subjects",
    courses: "Total published courses",
    teachers: "Teachers-Researchers with at least one course",
    topSubjects: "Top 10 Subjects",
    distributionBySubject: "Distribution by Subject",
    topTeachers: "Top 10 Teachers-Researchers",
    monthlyTrend: "Monthly Trend",
    subjectsDetail: "Subjects Detail",
    teachersDetail: "Teachers-Researchers Detail",
    subject: "Subject",
    courses: "Courses",
    percentage: "Percentage",
    teacher: "Teacher",
    publishedCourses: "Published Courses",
    addDiscipline: "Add Discipline",
    disciplineNamePlaceholder: "Discipline name",
    cancel: "Cancel",
    add: "Add",
    adding: "Adding...",
    disciplineAddedSuccess: "Discipline added successfully",
    disciplineAddError: "Error adding discipline",
    confirmRemoveDiscipline:
      "Are you sure you want to remove this discipline from the publication?",
    disciplineRemovedSuccess: "Discipline removed successfully",
    disciplineRemoveError: "Error removing discipline",
    locale: "en-US",
    allCoursesTitle: "All Available Courses",
    allCoursesSubtitle: "Browse all educational resources",
    loadingCourses: "Loading courses…",
    errorLoadingCourses: "Failed to load courses.",
    tryChangingFilters: "Try changing your filters.",
    retryButton: "Retry",
    filterCoursesLabel: "Filter courses",
    coursesFound: "{count}} course found",
    coursesFoundWithTotal: " {found}} of {total}}",
    resetFilters: "Reset filters",
    noCoursesAvailable: "No courses available",
    noCoursesYet: "No courses have been published yet.",
    noCoursesMatch: "No courses match your criteria",
    subjectUnspecified: "Unspecified",
    noDescription: "No description available.",
    attachedFile: "Attached File",
    download: "Download",
    noFilePreview: "No document to preview for this course.",
    instructorByLabel: "By {first}} {last}}",
    publishedOnLabel: "Published on {date}}",
    saveButton: "Save",
    createNewSubject: "Create New Subject",
    SubjectNamePlaceholder: "Subject Name",
    createAndAttach: "Create and Attach",
    createNew: "Create New",
    errorCreatingSubject: "Error creating subject",
    subjectNameRequired: "Subject name is required",
    errorOccurredCreating: "An error occurred while creating the subject",
    avgCitations: "Average Citations",
    subjectsTaught: "Taught Subjects",
    selectExistingDiscipline: "Select a discipline",
    selectOption: "Choose a discipline",
    loading: "Loading",
    errorLoadingDisciplines: "Error loading disciplines",
    disciplineAddedSuccess: "Discipline added successfully",
    disciplineAlreadyAttached:
      "This discipline is already attached to the publication",
    disciplineAddError: "Error adding discipline",
    confirmRemoveDiscipline: "Are you sure you want to remove this discipline?",
    disciplineRemovedSuccess: "Discipline removed successfully",
    disciplineRemoveError: "Error removing discipline",
    adding: "Adding...",
    aboutUsTitle: "About Us",
    aboutUsDescription:
      "We are a passionate team dedicated to providing innovative and tailored solutions for our clients. With years of experience and a human-centered approach, we transform ideas into digital reality while ensuring quality and satisfaction.",
    learnMoreButton: "Learn More",
    viewMorePublications: "View More Publications",
    viewMorePublications: "View More Publications",
    noPublicationsFound: "No publications found",
    pedagogy: "Pedagogy",
  },
};

export const LanguageContext = createContext({
  language: "fr",
  t: (key) => key,
  switchLanguage: () => {},
  formatDate: () => {},
  formatNumber: () => {},
  availableLanguages: ["fr", "en"],
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("fr");
  const [fallbackLanguage] = useState("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") || "fr";
    setLanguage(savedLang);
    document.documentElement.lang = savedLang;
  }, []);

  // Fonction de traduction
  const t = (key, params = {}) => {
    let translation =
      translations[language]?.[key] ||
      translations[fallbackLanguage][key] ||
      key;
    Object.entries(params).forEach(([paramKey, value]) => {
      translation = translation.replace(`{${paramKey}}}`, value);
    });
    return translation;
  };

  // Changer la langue
  const switchLanguage = (newLang) => {
    if (!translations[newLang]) return;
    localStorage.setItem("language", newLang);
    setLanguage(newLang);
    document.documentElement.lang = newLang;
  };

  // Formatage sécurisé des dates
  const formatDate = (dateInput, options = {}) => {
    const date = new Date(dateInput);
    if (isNaN(date.getTime())) {
      return (
        translations[language]?.["dateNotAvailable"] ||
        translations[fallbackLanguage]?.["dateNotAvailable"] ||
        "–"
      );
    }
    try {
      return new Intl.DateTimeFormat(language, options).format(date);
    } catch {
      return new Intl.DateTimeFormat(fallbackLanguage, options).format(date);
    }
  };

  // Formatage sécurisé des nombres
  const formatNumber = (number, options = {}) => {
    try {
      return new Intl.NumberFormat(language, options).format(number);
    } catch {
      return new Intl.NumberFormat(fallbackLanguage, options).format(number);
    }
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        t,
        switchLanguage,
        formatDate,
        formatNumber,
        availableLanguages: Object.keys(translations),
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

// Export par défaut pour faciliter l'import
export default LanguageContext;
