import React, { createContext, useState, useEffect } from "react";

export const translations = {
  fr: {
    home: "Accueil",
    researchers: "Chercheurs",
    publications: "Publications",
    news: "Actualités",
    about: "À propos",
    contact: "Contact",
    login: "Connexion",
    logout: "Déconnexion",
    myAccount: "Mon compte",
    settings: "Paramètres",
    language: "Langue",
    theme: "Thème",
    switchLanguage: "Changer la langue",
    calendar: "Calendrier",
    list: "Liste",
    next: "Suivant",
    previous: "Précédent",
    today: "Aujourd'hui",
    month: "Mois",
    week: "Semaine",
    day: "Jour",
    events: "Événements",
    showMore: "Voir plus",
    error404: "Page non trouvée",
    pageNotFound: "Désolé, nous n'avons pas trouvé la page que vous cherchez.",
    backToHome: "Retour à l'accueil",
    searchPublications: "Rechercher des publications...",
    filter: "Filtrer",
    year: "Année",
    domain: "Domaine",
    activeResearchers: "Chercheurs Actifs",
    citations: "Citations",
    profileError: "Erreur de récupération du profil",
    help: "Aide",
    contactSupport: "Contacter le support",
    more: "plus",
    loading: "Chargement...",
    welcomeMessage: "Bienvenue, {name}} !",
    appearance: "Apparence",
    lightTheme: "Thème clair",
    darkTheme: "Thème sombre",
    systemTheme: "Système",
    french: "Français",
    english: "Anglais",
    save: "Sauvegarder",
    close: "Fermer",
    back: "Retour",
    share: "Partager",
    comments: "Commentaires",
    downloadPDF: "Télécharger le PDF",
    abstract: "Résumé",
    name: "Nom",
    department: "Département",
    homeTitle: "Facilitez l’Accès aux Profils de Recherche",
    homeSubtitle:
      "Trouvez facilement les informations des chercheurs et leurs travaux scientifiques.",
    pageNotFoundTitle: "Page non trouvée",
    pageNotFoundDesc:
      "Désolé, nous n'avons pas trouvé la page que vous cherchez.",
    contactSupport: "Contacter le support",
    homeTitle: "Facilitez l’Accès aux Profils de Recherche",
    homeTitle: "Facilitez l’Accès aux Profils de Recherche",
    homeSubtitle:
      "Trouvez facilement les informations des chercheurs et leurs travaux scientifiques.",
    exploreResearchers: "Explorer les Chercheurs",
    learnMore: "En savoir plus",
    researchersCount: "Chercheurs",
    publicationsCount: "Publications",
    projectsCount: "Projets",
    countriesCount: "Pays",
    homeWelcomeTitle:
      "Bienvenue sur le Portail des Chercheurs [Page en cours de développement]",
    homeWelcomeText:
      "Accédez aux profils des chercheurs, découvrez leurs travaux et explorez les collaborations possibles.",
    abstractTitle: "Résumé",

    fullTextTitle: "Contenu Intégral",

    statsTitle: "Statistiques",

    citationsLabel: "Citations",

    downloadsLabel: "Téléchargements",

    downloadPdfBtn: "Télécharger le PDF",

    viewCitationsBtn: "Voir les citations",

    relatedPubsTitle: "Publications Associées",

    backBtnAria: "Retour",
    loading: "Chargement...",
    actualiteNotFoundTitle: "Actualité non trouvée",
    actualiteNotFoundDesc:
      "L'actualité demandée n'existe pas ou a été supprimée",
    dateLabel: "Le",
    categoryLabel: "Catégorie",
    backButton: "Retour",
    shareButton: "Partager",
    commentsTitle: "Commentaires",
    addCommentPlaceholder: "Ajouter un commentaire...",
    postCommentButton: "Publier",
    chercheursTitle: "Chercheurs",
    filterButton: "Filtrer",
    filterByName: "Nom",
    filterByDepartment: "Département",
    filterByPublications: "Publications",
    errorLoadingData: "Erreur lors du chargement des données",
    noResults: "Aucun résultat",
    closeButtonAria: "Fermer",
    agenda: "Agenda",
    adminNewsTitle: "Gestion des Actualités",
    addButton: "Ajouter",
    filterAll: "Toutes",
    filterFuture: "À venir",
    filterArchive: "Archivées",
    tableHeaderTitle: "Titre",
    tableHeaderLocation: "Localisation",
    tableHeaderDate: "Date",
    tableHeaderCategory: "Catégorie",
    tableHeaderActions: "Actions",
    noNewsFound: "Aucune actualité trouvée.",
    confirmDelete: "Confirmer la suppression ?",
    adminResearchersTitle: "Gestion des Chercheurs",
    adminLoginTitle: "Authentification Administrateur",
    emailLabel: "Email",
    emailPlaceholder: "admin@example.com",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "",
    loginButton: "Se connecter",
    profileError: "Erreur de récupération du profil",
    dashboardTitle: "Tableau de bord",
    createNewsTitle: "Créer une actualité",
    titrePlaceholder: "Titre",
    locationPlaceholder: "Localisation",
    descriptionPlaceholder: "Description",
    categoryPlaceholder: "Catégorie",
    addButton: "Ajouter",
    creationSuccess: "Actualité ajoutée avec succès !",
    creationError: "Erreur lors de l'ajout !",
    createResearcherTitle: "Créer un compte Chercheur",
    firstNameLabel: "Prénom",
    firstNamePlaceholder: "Prénom",
    lastNameLabel: "Nom",
    lastNamePlaceholder: "Nom",
    emailLabel: "Email",
    emailPlaceholder: "exemple@domaine.com",
    createAccountButton: "Créer le compte",
    researcherCreationSuccess: "Chercheur créé avec succès !",
    researcherCreationErrorPrefix: "Erreur lors de la création : ",
    unknownError: "Erreur inconnue",
    changePasswordTitle: "Changer le mot de passe",
    currentPasswordLabel: "Mot de passe actuel",
    currentPasswordPlaceholder: "••••••••",
    newPasswordLabel: "Nouveau mot de passe",
    newPasswordPlaceholder: "••••••••",
    confirmPasswordLabel: "Confirmer le nouveau mot de passe",
    confirmPasswordPlaceholder: "••••••••",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    passwordChangeSuccess: "Mot de passe changé avec succès !",
    passwordChangeError:
      "Une erreur s'est produite lors du changement de mot de passe.",
    saveButton: "Enregistrer",
    completeProfileFormTitle: "Complétez votre profil",
    scopusIdPlaceholder: "ID Scopus",
    disciplinePlaceholder: "Discipline",
    submitButton: "Valider",
    loading: "Chargement...",
    dashboardTitle: "Tableau de bord",
    statPublications: "Publications",
    statResearchers: "Chercheurs",
    statVisitors: "Visiteurs",
    chartTitle: "Statistiques des chercheurs",
    chartLabelResearchers: "Chercheurs",
    monthDec: "Déc",
    monthJan: "Jan",
    monthFeb: "Fév",
    monthMar: "Mar",
    monthApr: "Avr",
    monthMay: "Mai",
    monthJun: "Juin",
    upcomingEventTitle: "Événement à venir",
    upcomingEventDesc:
      "Découvrez les nouveautés et préparez-vous pour le prochain événement",
    viewMoreButton: "Voir plus",
    statsLoadError: "Erreur lors du chargement des statistiques :",
    loading: "Chargement...",
    profileLoadError: "Impossible de charger le profil.",
    universityLabel: "Université",
    contactButton: "Contacter",
    editButton: "Modifier",
    infoTitle: "Informations",
    departmentLabel: "Département",
    locationLabel: "Localisation",
    degreeLabel: "Diplôme",
    statsTitle: "Statistiques",
    statsPublications: "Publications",
    statsCitations: "Citations",
    statsHIndex: "H-index",
    statsProjects: "Projets de recherche",
    chartTitle: "Publications par année",
    publicationsTitle: "Publications",
    publicationsRecent: "récentes",
    viewAll: "Voir toutes ({{count}})",
    viewLess: "Voir moins",
    pubSearchPlaceholder: "Rechercher par titre...",
    pubFilterAll: "Toutes",
    pubFilterRecent: "Récentes",
    pubFilterMostCited: "Plus citées",
    noMorePublications: "Pas d'autres publications.",
    loginTitle: "Connexion Chercheur",
    loginSubtitle: "Accédez à votre espace de recherche",
    emailLabel: "Email Institutionnel",
    emailPlaceholder: "nom@institution.edu",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "••••••••",
    rememberMe: "Se souvenir de moi",
    forgotPassword: "Mot de passe oublié ?",
    loginButton: "Se connecter",
    loginError: "Identifiants invalides ou erreur serveur.",
    heroTitle: "ScholarHub",
    heroText:
      "Gérez votre profil de recherche et connectez-vous avec la communauté scientifique.",
    feature1: "Innovation et Recherche",
    feature2: "Collaboration Mondiale",
    feature3: "Publications Scientifiques",
    feature3: "Publications Scientifiques",
    manageResearchers: "Gestion des Chercheurs",
    searchResearchersPlaceholder: "Rechercher par nom, email ou domaine...",
    addResearcher: "Ajouter un chercheur",
    notSpecified: "Non spécifié",
    statusOnline: "En ligne",
    loading: "Chargement...",
    loadResearchersError: "Erreur lors du chargement des chercheurs",
    confirmDeleteResearcher: "Supprimer ce chercheur ?",
    deleteResearcherError: "Échec de la suppression. Veuillez réessayer.",
    tableHeaderName: "Nom",
    tableHeaderEmail: "Email",
    tableHeaderDomain: "Domaine",
    tableHeaderStatus: "Statut",
    tableHeaderActions: "Actions",
    selectAll: "Tout sélectionner",
    selectRow: "Sélectionner {{name}}",
    avatarAlt: "Photo de profil de {{name}}",
    statusOnline: "En ligne",
    editAction: "Modifier {{name}}",
    deleteAction: "Supprimer {{name}}",
    modalTitleEditNews: "Modifier l'actualité",
    titrePlaceholder: "Titre",
    locationPlaceholder: "Localisation",
    categoryPlaceholder: "Catégorie",
    descriptionPlaceholder: "Description",
    dashboard: "Tableau de bord",
    cancelButton: "Annuler",
    saveButton: "Sauvegarder",
    updateError: "Erreur lors de la mise à jour",
    modalTitleEditProfile:    "Modifier le profil",
    lastNameLabel:            "Nom",
    lastNamePlaceholder:      "Votre nom",
    firstNameLabel:           "Prénom",
    firstNamePlaceholder:     "Votre prénom",
    disciplinePlaceholder:    "Votre discipline",
    statusPlaceholder:        "Statut",
    aboutPlaceholder:         "À propos de moi...",
    noPhoto:                  "Aucune photo",
    changePhoto:              "Changer",
    removePhoto:              "Supprimer",
    importCV:                 "Importer CV",
    saveButton:               "Sauvegarder",
    saving:                   "Enregistrement",
    updateError:              "Erreur lors de la mise à jour",
    avatarAlt:                "Photo de profil de {{name}}",
    userNotFound:              "Utilisateur non trouvé ou non connecté",
    adminRole:                 "Administrateur",
    sideMenuAriaLabel: "Navigation latérale",
closeMenu: "Fermer le menu",
institutions: "Institutions",
security: "Sécurité",
publishedOn:        "Publié le :",
avatarAlt:       "Photo de profil de {{name}}",
departmentLabel: "Département",
publishedOn:     "Publié le :",
citationsLabel:  "Citations :",
viewPdfBtn:      "Voir le PDF",
shareButton:     "Partager",
searchPublications: "Rechercher des publications...",
year:               "Année",
domain:             "Domaine",
filter:             "Filtrer",
    profile: "Profil",
    sortAsc:  "▲",
    sortDesc: "▼",
    dateFormat: "dd MMMM yyyy"
  },

  en: {
    home: "Home",
    researchers: "Researchers",
    publications: "Publications",
    news: "News",
    about: "About",
    contact: "Contact",
    login: "Login",
    logout: "Logout",
    myAccount: "My Account",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    switchLanguage: "Switch language",
    calendar: "Calendar",
    list: "List",
    next: "Next",
    previous: "Previous",
    today: "Today",
    month: "Month",
    week: "Week",
    day: "Day",
    events: "Events",
    showMore: "Show more",
    error404: "Page not found",
    pageNotFound: "Sorry, we couldn't find the page you're looking for.",
    backToHome: "Back to home",
    searchPublications: "Search publications...",
    filter: "Filter",
    year: "Year",
    domain: "Domain",
    activeResearchers: "Active Researchers",
    citations: "Citations",
    profileError: "Error retrieving profile",
    help: "Help",
    contactSupport: "Contact support",
    more: "more",
    loading: "Loading...",
    welcomeMessage: "Welcome, {name}}!",
    appearance: "Appearance",
    lightTheme: "Light theme",
    darkTheme: "Dark theme",
    systemTheme: "System",
    french: "French",
    english: "English",
    save: "Save",
    close: "Close",
    back: "Back",
    share: "Share",
    comments: "Comments",
    downloadPDF: "Download PDF",
    abstract: "Abstract",
    name: "Name",
    department: "Department",
    homeTitle: "Facilitate Access to Research Profiles",
    homeSubtitle:
      "Easily find researcher information and their scientific work.",
    pageNotFoundTitle: "Page not found",
    pageNotFoundDesc: "Sorry, we couldn’t find the page you’re looking for.",
    contactSupport: "Contact support",
    homeTitle: "Facilitate Access to Research Profiles",
    homeSubtitle:
      "Easily find researcher information and their scientific work.",
    exploreResearchers: "Explore Researchers",
    learnMore: "Learn More",
    researchersCount: "Researchers",
    publicationsCount: "Publications",
    projectsCount: "Projects",
    countriesCount: "Countries",
    homeWelcomeTitle:
      "Welcome to the Researchers Portal [Page under development]",
    homeWelcomeText:
      "Access researcher profiles, discover their work, and explore possible collaborations.",
    abstractTitle: "Abstract",

    fullTextTitle: "Full Text",

    statsTitle: "Statistics",

    citationsLabel: "Citations",

    downloadsLabel: "Downloads",

    downloadPdfBtn: "Download PDF",

    viewCitationsBtn: "View Citations",

    relatedPubsTitle: "Related Publications",

    backBtnAria: "Go back",
    loading: "Loading...",
    actualiteNotFoundTitle: "News Not Found",
    actualiteNotFoundDesc:
      "The requested news item does not exist or has been deleted",
    dateLabel: "On",
    categoryLabel: "Category",
    backButton: "Back",
    shareButton: "Share",
    commentsTitle: "Comments",
    addCommentPlaceholder: "Add a comment...",
    postCommentButton: "Post",
    chercheursTitle: "Researchers",
    filterButton: "Filter",
    filterByName: "Name",
    filterByDepartment: "Department",
    filterByPublications: "Publications",
    errorLoadingData: "Error loading data",
    noResults: "No results",
    closeButtonAria: "Close",
    agenda: "Agenda",
    adminNewsTitle: "News Management",
    addButton: "Add",
    filterAll: "All",
    filterFuture: "Upcoming",
    filterArchive: "Archived",
    tableHeaderTitle: "Title",
    tableHeaderLocation: "Location",
    tableHeaderDate: "Date",
    tableHeaderCategory: "Category",
    tableHeaderActions: "Actions",
    noNewsFound: "No news found.",
    confirmDelete: "Confirm deletion?",
    adminResearchersTitle: "Researchers Management",
    adminLoginTitle: "Administrator Login",
    emailLabel: "Email",
    emailPlaceholder: "admin@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "",
    loginButton: "Log in",
    profileError: "Error retrieving profile",
    dashboardTitle: "Dashboard",
    createNewsTitle: "Create News",
    titrePlaceholder: "Title",
    locationPlaceholder: "Location",
    descriptionPlaceholder: "Description",
    categoryPlaceholder: "Category",
    addButton: "Add",
    creationSuccess: "News created successfully!",
    creationError: "Error creating news!",
    createResearcherTitle: "Create Researcher Account",
    firstNameLabel: "First Name",
    firstNamePlaceholder: "First Name",
    lastNameLabel: "Last Name",
    lastNamePlaceholder: "Last Name",
    emailLabel: "Email",
    emailPlaceholder: "example@domain.com",
    createAccountButton: "Create Account",
    researcherCreationSuccess: "Researcher created successfully!",
    researcherCreationErrorPrefix: "Error creating researcher: ",
    unknownError: "Unknown error",
    changePasswordTitle: "Change Password",
    currentPasswordLabel: "Current Password",
    currentPasswordPlaceholder: "••••••••",
    newPasswordLabel: "New Password",
    newPasswordPlaceholder: "••••••••",
    confirmPasswordLabel: "Confirm New Password",
    confirmPasswordPlaceholder: "••••••••",
    passwordMismatch: "Passwords do not match.",
    passwordChangeSuccess: "Password changed successfully!",
    passwordChangeError: "An error occurred while changing the password.",
    saveButton: "Save",
    completeProfileFormTitle: "Complete your profile",
    scopusIdPlaceholder: "Scopus ID",
    disciplinePlaceholder: "Discipline",
    submitButton: "Submit",
    loading: "Loading...",
    dashboardTitle: "Dashboard",
    statPublications: "Publications",
    statResearchers: "Researchers",
    statVisitors: "Visitors",
    chartTitle: "Researchers Statistics",
    chartLabelResearchers: "Researchers",
    monthDec: "Dec",
    monthJan: "Jan",
    monthFeb: "Feb",
    monthMar: "Mar",
    monthApr: "Apr",
    monthMay: "May",
    monthJun: "Jun",
    upcomingEventTitle: "Upcoming Event",
    upcomingEventDesc: "Discover updates and prepare for the next event",
    viewMoreButton: "View more",
    statsLoadError: "Error loading statistics:",
    loading: "Loading...",
    profileLoadError: "Unable to load profile.",
    universityLabel: "University",
    contactButton: "Contact",
    editButton: "Edit",
    infoTitle: "Information",
    departmentLabel: "Department",
    locationLabel: "Location",
    degreeLabel: "Degree",
    statsTitle: "Statistics",
    statsPublications: "Publications",
    statsCitations: "Citations",
    statsHIndex: "H-index",
    statsProjects: "Research projects",
    chartTitle: "Publications by year",
    publicationsTitle: "Publications",
    publicationsRecent: "recent",
    viewAll: "View all ({{count}})",
    viewLess: "View less",
    pubSearchPlaceholder: "Search by title...",
    pubFilterAll: "All",
    pubFilterRecent: "Recent",
    pubFilterMostCited: "Most cited",
    noMorePublications: "No more publications.",
    loginTitle: "Researcher Login",
    loginSubtitle: "Access your research workspace",
    emailLabel: "Institutional Email",
    emailPlaceholder: "name@institution.edu",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    loginButton: "Log in",
    loginError: "Invalid credentials or server error.",
    heroTitle: "ScholarHub",
    heroText:
      "Manage your research profile and connect with the scientific community.",
    feature1: "Innovation & Research",
    feature2: "Global Collaboration",
    feature3: "Scientific Publications",
    manageResearchers: "Researchers Management",
    searchResearchersPlaceholder: "Search by name, email or domain...",
    addResearcher: "Add Researcher",
    notSpecified: "Not specified",
    statusOnline: "Online",
    loading: "Loading...",
    loadResearchersError: "Error loading researchers",
    confirmDeleteResearcher: "Delete this researcher?",
    deleteResearcherError: "Deletion failed. Please try again.",
    tableHeaderName: "Name",
    tableHeaderEmail: "Email",
    tableHeaderDomain: "Domain",
    tableHeaderStatus: "Status",
    tableHeaderActions: "Actions",
    selectAll: "Select all",
    selectRow: "Select {{name}}",
    avatarAlt: "{{name}}'s avatar",
    statusOnline: "Online",
    editAction: "Edit {{name}}",
    deleteAction: "Delete {{name}}",
    modalTitleEditNews: "Edit News",
    titrePlaceholder: "Title",
    locationPlaceholder: "Location",
    categoryPlaceholder: "Category",
    descriptionPlaceholder: "Description",
    dashboard: "Dashboard",
    cancelButton: "Cancel",
    saveButton: "Save",
    updateError: "Error updating news",
    modalTitleEditProfile:    "Edit Profile",
    lastNameLabel:            "Last Name",
    lastNamePlaceholder:      "Your last name",
    firstNameLabel:           "First Name",
    firstNamePlaceholder:     "Your first name",
    disciplinePlaceholder:    "Your discipline",
    statusPlaceholder:        "Status",
    aboutPlaceholder:         "About me...",
    noPhoto:                  "No photo",
    changePhoto:              "Change",
    removePhoto:              "Remove",
    importCV:                 "Import CV",
    saveButton:               "Save",
    saving:                   "Saving",
    updateError:              "Error updating",
    avatarAlt:                "{{name}}'s avatar",
    userNotFound:              "User not found or not logged in",
    adminRole:                 "Administrator",
    sideMenuAriaLabel: "Side navigation",
closeMenu: "Close menu",
institutions: "Institutions",
security: "Security",
publishedOn:        "Published on:",
avatarAlt:       "{{name}}'s avatar",
departmentLabel : "Department",
publishedOn:     "Published on:",
citationsLabel:  "Citations:",
viewPdfBtn:      "View PDF",
shareButton:     "Share",
    profile: "Profile",
    sortAsc:  "▲",
    sortDesc: "▼",
    dateFormat: "dd MMMM yyyy"
  },
};

export const LanguageContext = createContext({
  language: "fr",
  t: (key) => key,
  switchLanguage: () => {},
  formatDate: () => {},
  formatNumber: () => {},
  availableLanguages: ["fr", "en"],
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("fr");
  const [fallbackLanguage] = useState("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") || "fr";
    setLanguage(savedLang);
    document.documentElement.lang = savedLang;
  }, []);

  const t = (key, params = {}) => {
    let translation =
      translations[language]?.[key] ||
      translations[fallbackLanguage][key] ||
      key;

    Object.entries(params).forEach(([paramKey, value]) => {
      translation = translation.replace(`{${paramKey}}}`, value);
    });

    return translation;
  };

  const switchLanguage = (newLang) => {
    if (!translations[newLang]) return;
    localStorage.setItem("language", newLang);
    setLanguage(newLang);
    document.documentElement.lang = newLang;
  };

  const formatDate = (date, options = {}) => {
    try {
      return new Intl.DateTimeFormat(language, options).format(new Date(date));
    } catch {
      return new Intl.DateTimeFormat(fallbackLanguage, options).format(
        new Date(date)
      );
    }
  };

  const formatNumber = (number, options = {}) => {
    try {
      return new Intl.NumberFormat(language, options).format(number);
    } catch {
      return new Intl.NumberFormat(fallbackLanguage, options).format(number);
    }
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        t,
        switchLanguage,
        formatDate,
        formatNumber,
        availableLanguages: Object.keys(translations),
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};
